      SUBROUTINE SMATRIX2(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.4.3, 2016-08-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g u~ > b1 b1~ g u~ WEIGHTED<=4 @3
C     Process: g c~ > b1 b1~ g c~ WEIGHTED<=4 @3
C     Process: g d~ > b1 b1~ g d~ WEIGHTED<=4 @3
C     Process: g s~ > b1 b1~ g s~ WEIGHTED<=4 @3
C     
      USE DISCRETESAMPLER
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=108)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=87)
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     global (due to reading writting) 
C     
      LOGICAL GOODHEL(NCOMB,2)
      INTEGER NTRY(2)
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      INTEGER ISHEL(2)
      REAL*8 T,MATRIX2
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER NGOOD(2), IGOOD(NCOMB,2)
      INTEGER JHEL(2), J, JJ
      INTEGER THIS_NTRY(2)
      SAVE THIS_NTRY
      DATA THIS_NTRY /0,0/
C     This is just to temporarily store the reference grid for
C      helicity of the DiscreteSampler so as to obtain its number of
C      entries with ref_helicity_grid%n_tot_entries
      TYPE(SAMPLEDDIMENSION) REF_HELICITY_GRID
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2

      CHARACTER*101         HEL_BUFF
      COMMON/TO_HELICITY/  HEL_BUFF

      INTEGER IMIRROR
      COMMON/TO_MIRROR/ IMIRROR

      REAL*8 POL(2)
      COMMON/TO_POLARIZATION/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      DATA XTRY, XREJ /0,0/
      DATA NGOOD /0,0/
      DATA ISHEL/0,0/
      SAVE YFRAC, IGOOD, JHEL
      DATA (NHEL(I,   1),I=1,6) /-1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,   5),I=1,6) /-1, 1, 0, 0,-1, 1/
      DATA (NHEL(I,   6),I=1,6) /-1, 1, 0, 0,-1,-1/
      DATA (NHEL(I,   7),I=1,6) /-1, 1, 0, 0, 1, 1/
      DATA (NHEL(I,   8),I=1,6) /-1, 1, 0, 0, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1, 1, 0, 0,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1, 1, 0, 0,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1, 1, 0, 0, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1, 1, 0, 0, 1,-1/
      DATA IDEN/96/

C     To be able to control when the matrix<i> subroutine can add
C      entries to the grid for the MC over helicity configuration
      LOGICAL ALLOW_HELICITY_GRID_ENTRIES
      COMMON/TO_ALLOW_HELICITY_GRID_ENTRIES/ALLOW_HELICITY_GRID_ENTRIES

C     ----------
C     BEGIN CODE
C     ----------
      NTRY(IMIRROR)=NTRY(IMIRROR)+1
      THIS_NTRY(IMIRROR) = THIS_NTRY(IMIRROR)+1
      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
        JAMP2(0)=12
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
      ENDIF
      ANS = 0D0
      WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL)
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO

        !   If the helicity grid status is 0, this means that it is not yet initialized.
        !   If HEL_PICKED==-1, this means that calls to other matrix<i> where in initialization mode as well for the helicity.
      IF ((ISHEL(IMIRROR).EQ.0.AND.ISUM_HEL.EQ.0).OR.(DS_GET_DIM_STATUS
     $('Helicity').EQ.0).OR.(HEL_PICKED.EQ.-1)) THEN
        DO I=1,NCOMB
          IF (GOODHEL(I,IMIRROR) .OR. NTRY(IMIRROR).LE.MAXTRIES.OR.(ISU
     $M_HEL.NE.0).OR.THIS_NTRY(IMIRROR).LE.2) THEN
            T=MATRIX2(P ,NHEL(1,I),JC(1))
            DO JJ=1,NINCOMING
              IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))
     $         )) THEN
                T=T*ABS(POL(JJ))
              ELSE IF(POL(JJ).NE.1D0)THEN
                T=T*(2D0-ABS(POL(JJ)))
              ENDIF
            ENDDO
            IF (ISUM_HEL.NE.0.AND.DS_GET_DIM_STATUS('Helicity')
     $       .EQ.0.AND.ALLOW_HELICITY_GRID_ENTRIES) THEN
              CALL DS_ADD_ENTRY('Helicity',I,T)
            ENDIF
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        IF(NTRY(IMIRROR).EQ.(MAXTRIES+1)) THEN
          CALL RESET_CUMULATIVE_VARIABLE()  ! avoid biais of the initialization
        ENDIF
        IF (ISUM_HEL.NE.0) THEN
            !         We set HEL_PICKED to -1 here so that later on, the call to DS_add_point in dsample.f does not add anything to the grid since it was already done here.
          HEL_PICKED = -1
            !         For safety, hardset the helicity sampling jacobian to 0.0d0 to make sure it is not .
          HEL_JACOBIAN   = 1.0D0
            !         We don't want to re-update the helicity grid if it was already updated by another matrix<i>, so we make sure that the reference grid is empty.
          REF_HELICITY_GRID = DS_GET_DIMENSION(REF_GRID,'Helicity')
          IF((DS_GET_DIM_STATUS('Helicity').EQ.1).AND.(REF_HELICITY_GRI
     $D%N_TOT_ENTRIES.EQ.0)) THEN
              !           If we finished the initialization we can update the grid so as to start sampling over it.
              !           However the grid will now be filled by dsample with different kind of weights (including pdf, flux, etc...) so by setting the grid_mode of the reference grid to 'initialization' we make sure it will be overwritten (as opposed to 'combined') by the running grid at the next update.
            CALL DS_UPDATE_GRID('Helicity')
            CALL DS_SET_GRID_MODE('Helicity','init')
          ENDIF
        ELSE
          JHEL(IMIRROR) = 1
          IF(NTRY(IMIRROR).LE.MAXTRIES.OR.THIS_NTRY(IMIRROR).LE.2)THEN
            DO I=1,NCOMB
              IF (.NOT.GOODHEL(I,IMIRROR) .AND. (DABS(TS(I)).GT.ANS
     $         *LIMHEL/NCOMB)) THEN
                GOODHEL(I,IMIRROR)=.TRUE.
                NGOOD(IMIRROR) = NGOOD(IMIRROR) +1
                IGOOD(NGOOD(IMIRROR),IMIRROR) = I
                PRINT *,'Added good helicity ',I,TS(I)*NCOMB/ANS,' in'
     $           //' event ',NTRY(IMIRROR), 'local:',THIS_NTRY(IMIRROR)
              ENDIF
            ENDDO
          ENDIF
          IF(NTRY(IMIRROR).EQ.MAXTRIES)THEN
            ISHEL(IMIRROR)=MIN(ISUM_HEL,NGOOD(IMIRROR))
          ENDIF
        ENDIF
      ELSE  ! random helicity 
C       The helicity configuration was chosen already by genps and put
C        in a common block defined in genps.inc.
        I = HEL_PICKED

        T=MATRIX2(P ,NHEL(1,I),JC(1))

        DO JJ=1,NINCOMING
          IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))
          ELSE IF(POL(JJ).NE.1D0)THEN
            T=T*(2D0-ABS(POL(JJ)))
          ENDIF
        ENDDO
C       Always one helicity at a time
        ANS = T
C       Include the Jacobian from helicity sampling
        ANS = ANS * HEL_JACOBIAN

        WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
      ENDIF
      IF (ANS.NE.0D0.AND.(ISUM_HEL .NE. 1.OR.HEL_PICKED.EQ.-1)) THEN
        CALL RANMAR(R)
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(R.LT.SUMHEL)THEN
            WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(2))/XTOT
        ELSE
          ANS=0D0
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX2(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.4.3, 2016-08-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g u~ > b1 b1~ g u~ WEIGHTED<=4 @3
C     Process: g c~ > b1 b1~ g c~ WEIGHTED<=4 @3
C     Process: g d~ > b1 b1~ g d~ WEIGHTED<=4 @3
C     Process: g s~ > b1 b1~ g s~ WEIGHTED<=4 @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=108)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=19, NCOLOR=12)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX2
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/3/
      DATA (CF(I,  1),I=  1,  6) /   48,   16,   16,    6,    0,   16/
      DATA (CF(I,  1),I=  7, 12) /   -2,    0,    0,   16,   -2,    0/
C     1 T(1,2,4) T(5,3,6)
      DATA DENOM(2)/3/
      DATA (CF(I,  2),I=  1,  6) /   16,   48,    6,   16,   16,    0/
      DATA (CF(I,  2),I=  7, 12) /    0,   -2,   16,    0,    0,   -2/
C     1 T(1,2,6) T(5,3,4)
      DATA DENOM(3)/3/
      DATA (CF(I,  3),I=  1,  6) /   16,    6,   48,   16,   -2,    0/
      DATA (CF(I,  3),I=  7, 12) /    0,   16,   -2,    0,    0,   16/
C     1 T(1,3,4) T(5,2,6)
      DATA DENOM(4)/3/
      DATA (CF(I,  4),I=  1,  6) /    6,   16,   16,   48,    0,   -2/
      DATA (CF(I,  4),I=  7, 12) /   16,    0,    0,   -2,   16,    0/
C     1 T(1,3,6) T(5,2,4)
      DATA DENOM(5)/3/
      DATA (CF(I,  5),I=  1,  6) /    0,   16,   -2,    0,   48,   16/
      DATA (CF(I,  5),I=  7, 12) /   16,    6,    6,   -2,   -2,   -6/
C     1 T(1,5,2,4) T(3,6)
      DATA DENOM(6)/3/
      DATA (CF(I,  6),I=  1,  6) /   16,    0,    0,   -2,   16,   48/
      DATA (CF(I,  6),I=  7, 12) /    6,   16,   -2,    6,   -6,   -2/
C     1 T(1,5,2,6) T(3,4)
      DATA DENOM(7)/3/
      DATA (CF(I,  7),I=  1,  6) /   -2,    0,    0,   16,   16,    6/
      DATA (CF(I,  7),I=  7, 12) /   48,   16,   -2,   -6,    6,   -2/
C     1 T(1,5,3,4) T(2,6)
      DATA DENOM(8)/3/
      DATA (CF(I,  8),I=  1,  6) /    0,   -2,   16,    0,    6,   16/
      DATA (CF(I,  8),I=  7, 12) /   16,   48,   -6,   -2,   -2,    6/
C     1 T(1,5,3,6) T(2,4)
      DATA DENOM(9)/3/
      DATA (CF(I,  9),I=  1,  6) /    0,   16,   -2,    0,    6,   -2/
      DATA (CF(I,  9),I=  7, 12) /   -2,   -6,   48,   16,   16,    6/
C     1 T(2,4) T(5,1,3,6)
      DATA DENOM(10)/3/
      DATA (CF(I, 10),I=  1,  6) /   16,    0,    0,   -2,   -2,    6/
      DATA (CF(I, 10),I=  7, 12) /   -6,   -2,   16,   48,    6,   16/
C     1 T(2,6) T(5,1,3,4)
      DATA DENOM(11)/3/
      DATA (CF(I, 11),I=  1,  6) /   -2,    0,    0,   16,   -2,   -6/
      DATA (CF(I, 11),I=  7, 12) /    6,   -2,   16,    6,   48,   16/
C     1 T(3,4) T(5,1,2,6)
      DATA DENOM(12)/3/
      DATA (CF(I, 12),I=  1,  6) /    0,   -2,   16,    0,   -6,   -2/
      DATA (CF(I, 12),I=  7, 12) /   -2,    6,    6,   16,   16,   48/
C     1 T(3,6) T(5,1,2,4)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL SXXXXX(P(0,4),+1*IC(4),W(1,4))
      CALL VXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL VVV1P0_1(W(1,1),W(1,5),GC_6,ZERO,ZERO,W(1,7))
      CALL VSS1P0_1(W(1,4),W(1,3),GC_71,ZERO,ZERO,W(1,8))
      CALL FFV1_1(W(1,2),W(1,7),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,6),W(1,9),W(1,8),GC_7,AMP(1))
      CALL FFV1_2(W(1,6),W(1,7),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,9),W(1,2),W(1,8),GC_7,AMP(2))
      CALL FFV1P0_3(W(1,6),W(1,2),GC_7,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,7),W(1,8),W(1,9),GC_6,AMP(3))
C     Amplitude(s) for diagram number 4
      CALL VVSS1_0(W(1,7),W(1,9),W(1,4),W(1,3),GC_18,AMP(4))
      CALL VVSS1_0(W(1,7),W(1,9),W(1,4),W(1,3),GC_18,AMP(5))
      CALL VSS1_2(W(1,7),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,10))
C     Amplitude(s) for diagram number 5
      CALL VSS1_0(W(1,9),W(1,4),W(1,10),GC_71,AMP(6))
      CALL VSS1_3(W(1,7),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,10))
C     Amplitude(s) for diagram number 6
      CALL VSS1_0(W(1,9),W(1,4),W(1,10),GC_73,AMP(7))
      CALL VSS1_3(W(1,7),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,10))
C     Amplitude(s) for diagram number 7
      CALL VSS1_0(W(1,9),W(1,10),W(1,3),GC_71,AMP(8))
      CALL VSS1_3(W(1,7),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,10))
C     Amplitude(s) for diagram number 8
      CALL VSS1_0(W(1,9),W(1,3),W(1,10),GC_79,AMP(9))
      CALL VSS1_2(W(1,1),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,10))
      CALL VSS1_3(W(1,5),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,7))
C     Amplitude(s) for diagram number 9
      CALL VSS1_0(W(1,9),W(1,7),W(1,10),GC_71,AMP(10))
      CALL VSS1_3(W(1,5),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,11))
C     Amplitude(s) for diagram number 10
      CALL VSS1_0(W(1,9),W(1,10),W(1,11),GC_79,AMP(11))
      CALL VSS1_3(W(1,1),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,12))
C     Amplitude(s) for diagram number 11
      CALL VSS1_0(W(1,9),W(1,7),W(1,12),GC_73,AMP(12))
C     Amplitude(s) for diagram number 12
      CALL VSS1_0(W(1,9),W(1,11),W(1,12),GC_81,AMP(13))
      CALL FFV1_1(W(1,2),W(1,5),GC_7,ZERO,ZERO,W(1,13))
      CALL VSS1P0_1(W(1,4),W(1,10),GC_71,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,6),W(1,13),W(1,14),GC_7,AMP(14))
      CALL VSS1P0_1(W(1,4),W(1,12),GC_73,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,6),W(1,13),W(1,15),GC_7,AMP(15))
      CALL FFV1_2(W(1,6),W(1,5),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,16),W(1,2),W(1,14),GC_7,AMP(16))
C     Amplitude(s) for diagram number 16
      CALL FFV1_0(W(1,16),W(1,2),W(1,15),GC_7,AMP(17))
C     Amplitude(s) for diagram number 17
      CALL VVSS1_0(W(1,5),W(1,9),W(1,4),W(1,10),GC_18,AMP(18))
      CALL VVSS1_0(W(1,5),W(1,9),W(1,4),W(1,10),GC_18,AMP(19))
      CALL VSS1_2(W(1,5),W(1,10),GC_71,MDL_MSD3,MDL_WSD3,W(1,17))
C     Amplitude(s) for diagram number 18
      CALL VSS1_0(W(1,9),W(1,4),W(1,17),GC_71,AMP(20))
      CALL VSS1_3(W(1,5),W(1,10),GC_79,MDL_MSD6,MDL_WSD6,W(1,17))
C     Amplitude(s) for diagram number 19
      CALL VSS1_0(W(1,9),W(1,4),W(1,17),GC_73,AMP(21))
C     Amplitude(s) for diagram number 20
      CALL VVV1_0(W(1,5),W(1,9),W(1,14),GC_6,AMP(22))
C     Amplitude(s) for diagram number 21
      CALL VVSS1_0(W(1,5),W(1,9),W(1,4),W(1,12),GC_21,AMP(23))
      CALL VVSS1_0(W(1,5),W(1,9),W(1,4),W(1,12),GC_21,AMP(24))
      CALL VSS1_2(W(1,5),W(1,12),GC_73,MDL_MSD3,MDL_WSD3,W(1,14))
C     Amplitude(s) for diagram number 22
      CALL VSS1_0(W(1,9),W(1,4),W(1,14),GC_71,AMP(25))
      CALL VSS1_2(W(1,5),W(1,12),GC_81,MDL_MSD6,MDL_WSD6,W(1,14))
C     Amplitude(s) for diagram number 23
      CALL VSS1_0(W(1,9),W(1,4),W(1,14),GC_73,AMP(26))
C     Amplitude(s) for diagram number 24
      CALL VVV1_0(W(1,5),W(1,9),W(1,15),GC_6,AMP(27))
      CALL VSS1_3(W(1,1),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,15))
      CALL VSS1_2(W(1,5),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,14))
C     Amplitude(s) for diagram number 25
      CALL VSS1_0(W(1,9),W(1,15),W(1,14),GC_71,AMP(28))
      CALL VSS1_3(W(1,5),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,12))
C     Amplitude(s) for diagram number 26
      CALL VSS1_0(W(1,9),W(1,15),W(1,12),GC_73,AMP(29))
      CALL VSS1_3(W(1,1),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,17))
C     Amplitude(s) for diagram number 27
      CALL VSS1_0(W(1,9),W(1,14),W(1,17),GC_79,AMP(30))
C     Amplitude(s) for diagram number 28
      CALL VSS1_0(W(1,9),W(1,17),W(1,12),GC_81,AMP(31))
      CALL VSS1P0_1(W(1,15),W(1,3),GC_71,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 29
      CALL FFV1_0(W(1,6),W(1,13),W(1,10),GC_7,AMP(32))
      CALL VSS1P0_1(W(1,3),W(1,17),GC_79,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 30
      CALL FFV1_0(W(1,6),W(1,13),W(1,18),GC_7,AMP(33))
C     Amplitude(s) for diagram number 31
      CALL FFV1_0(W(1,16),W(1,2),W(1,10),GC_7,AMP(34))
C     Amplitude(s) for diagram number 32
      CALL FFV1_0(W(1,16),W(1,2),W(1,18),GC_7,AMP(35))
C     Amplitude(s) for diagram number 33
      CALL VVSS1_0(W(1,5),W(1,9),W(1,15),W(1,3),GC_18,AMP(36))
      CALL VVSS1_0(W(1,5),W(1,9),W(1,15),W(1,3),GC_18,AMP(37))
      CALL VSS1_3(W(1,5),W(1,15),GC_71,MDL_MSD3,MDL_WSD3,W(1,19))
C     Amplitude(s) for diagram number 34
      CALL VSS1_0(W(1,9),W(1,19),W(1,3),GC_71,AMP(38))
      CALL VSS1_3(W(1,5),W(1,15),GC_73,MDL_MSD6,MDL_WSD6,W(1,19))
C     Amplitude(s) for diagram number 35
      CALL VSS1_0(W(1,9),W(1,3),W(1,19),GC_79,AMP(39))
C     Amplitude(s) for diagram number 36
      CALL VVV1_0(W(1,5),W(1,9),W(1,10),GC_6,AMP(40))
C     Amplitude(s) for diagram number 37
      CALL VVSS1_0(W(1,5),W(1,9),W(1,3),W(1,17),GC_21,AMP(41))
      CALL VVSS1_0(W(1,5),W(1,9),W(1,3),W(1,17),GC_21,AMP(42))
      CALL VSS1_2(W(1,5),W(1,17),GC_79,MDL_MSD3,MDL_WSD3,W(1,10))
C     Amplitude(s) for diagram number 38
      CALL VSS1_0(W(1,9),W(1,10),W(1,3),GC_71,AMP(43))
      CALL VSS1_3(W(1,5),W(1,17),GC_81,MDL_MSD6,MDL_WSD6,W(1,10))
C     Amplitude(s) for diagram number 39
      CALL VSS1_0(W(1,9),W(1,3),W(1,10),GC_79,AMP(44))
C     Amplitude(s) for diagram number 40
      CALL VVV1_0(W(1,5),W(1,9),W(1,18),GC_6,AMP(45))
      CALL FFV1_1(W(1,2),W(1,1),GC_7,ZERO,ZERO,W(1,18))
      CALL FFV1P0_3(W(1,6),W(1,18),GC_7,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 41
      CALL VSS1_0(W(1,10),W(1,4),W(1,14),GC_71,AMP(46))
C     Amplitude(s) for diagram number 42
      CALL VSS1_0(W(1,10),W(1,4),W(1,12),GC_73,AMP(47))
C     Amplitude(s) for diagram number 43
      CALL VSS1_0(W(1,10),W(1,7),W(1,3),GC_71,AMP(48))
C     Amplitude(s) for diagram number 44
      CALL VSS1_0(W(1,10),W(1,3),W(1,11),GC_79,AMP(49))
C     Amplitude(s) for diagram number 45
      CALL FFV1_0(W(1,16),W(1,18),W(1,8),GC_7,AMP(50))
      CALL FFV1_1(W(1,18),W(1,5),GC_7,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 46
      CALL FFV1_0(W(1,6),W(1,17),W(1,8),GC_7,AMP(51))
C     Amplitude(s) for diagram number 47
      CALL VVV1_0(W(1,5),W(1,8),W(1,10),GC_6,AMP(52))
      CALL VVSS1P0_1(W(1,5),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,10))
      CALL VVSS1P0_1(W(1,5),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 48
      CALL FFV1_0(W(1,6),W(1,18),W(1,10),GC_7,AMP(53))
      CALL FFV1_0(W(1,6),W(1,18),W(1,17),GC_7,AMP(54))
      CALL FFV1_2(W(1,6),W(1,1),GC_7,ZERO,ZERO,W(1,18))
      CALL FFV1P0_3(W(1,18),W(1,2),GC_7,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 49
      CALL VSS1_0(W(1,19),W(1,4),W(1,14),GC_71,AMP(55))
C     Amplitude(s) for diagram number 50
      CALL VSS1_0(W(1,19),W(1,4),W(1,12),GC_73,AMP(56))
C     Amplitude(s) for diagram number 51
      CALL VSS1_0(W(1,19),W(1,7),W(1,3),GC_71,AMP(57))
C     Amplitude(s) for diagram number 52
      CALL VSS1_0(W(1,19),W(1,3),W(1,11),GC_79,AMP(58))
C     Amplitude(s) for diagram number 53
      CALL FFV1_0(W(1,18),W(1,13),W(1,8),GC_7,AMP(59))
      CALL FFV1_2(W(1,18),W(1,5),GC_7,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 54
      CALL FFV1_0(W(1,15),W(1,2),W(1,8),GC_7,AMP(60))
C     Amplitude(s) for diagram number 55
      CALL VVV1_0(W(1,5),W(1,8),W(1,19),GC_6,AMP(61))
C     Amplitude(s) for diagram number 56
      CALL FFV1_0(W(1,18),W(1,2),W(1,10),GC_7,AMP(62))
      CALL FFV1_0(W(1,18),W(1,2),W(1,17),GC_7,AMP(63))
C     Amplitude(s) for diagram number 57
      CALL VVSS1_0(W(1,1),W(1,9),W(1,4),W(1,14),GC_18,AMP(64))
      CALL VVSS1_0(W(1,1),W(1,9),W(1,4),W(1,14),GC_18,AMP(65))
      CALL VSS1_2(W(1,1),W(1,14),GC_71,MDL_MSD3,MDL_WSD3,W(1,18))
C     Amplitude(s) for diagram number 58
      CALL VSS1_0(W(1,9),W(1,4),W(1,18),GC_71,AMP(66))
      CALL VSS1_3(W(1,1),W(1,14),GC_79,MDL_MSD6,MDL_WSD6,W(1,18))
C     Amplitude(s) for diagram number 59
      CALL VSS1_0(W(1,9),W(1,4),W(1,18),GC_73,AMP(67))
      CALL VVV1P0_1(W(1,1),W(1,9),GC_6,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 60
      CALL VSS1_0(W(1,18),W(1,4),W(1,14),GC_71,AMP(68))
C     Amplitude(s) for diagram number 61
      CALL VVSS1_0(W(1,1),W(1,9),W(1,4),W(1,12),GC_21,AMP(69))
      CALL VVSS1_0(W(1,1),W(1,9),W(1,4),W(1,12),GC_21,AMP(70))
      CALL VSS1_2(W(1,1),W(1,12),GC_73,MDL_MSD3,MDL_WSD3,W(1,14))
C     Amplitude(s) for diagram number 62
      CALL VSS1_0(W(1,9),W(1,4),W(1,14),GC_71,AMP(71))
      CALL VSS1_2(W(1,1),W(1,12),GC_81,MDL_MSD6,MDL_WSD6,W(1,14))
C     Amplitude(s) for diagram number 63
      CALL VSS1_0(W(1,9),W(1,4),W(1,14),GC_73,AMP(72))
C     Amplitude(s) for diagram number 64
      CALL VSS1_0(W(1,18),W(1,4),W(1,12),GC_73,AMP(73))
C     Amplitude(s) for diagram number 65
      CALL VVSS1_0(W(1,1),W(1,9),W(1,7),W(1,3),GC_18,AMP(74))
      CALL VVSS1_0(W(1,1),W(1,9),W(1,7),W(1,3),GC_18,AMP(75))
      CALL VSS1_3(W(1,1),W(1,7),GC_71,MDL_MSD3,MDL_WSD3,W(1,12))
C     Amplitude(s) for diagram number 66
      CALL VSS1_0(W(1,9),W(1,12),W(1,3),GC_71,AMP(76))
      CALL VSS1_3(W(1,1),W(1,7),GC_73,MDL_MSD6,MDL_WSD6,W(1,12))
C     Amplitude(s) for diagram number 67
      CALL VSS1_0(W(1,9),W(1,3),W(1,12),GC_79,AMP(77))
C     Amplitude(s) for diagram number 68
      CALL VSS1_0(W(1,18),W(1,7),W(1,3),GC_71,AMP(78))
C     Amplitude(s) for diagram number 69
      CALL VVSS1_0(W(1,1),W(1,9),W(1,3),W(1,11),GC_21,AMP(79))
      CALL VVSS1_0(W(1,1),W(1,9),W(1,3),W(1,11),GC_21,AMP(80))
      CALL VSS1_2(W(1,1),W(1,11),GC_79,MDL_MSD3,MDL_WSD3,W(1,7))
C     Amplitude(s) for diagram number 70
      CALL VSS1_0(W(1,9),W(1,7),W(1,3),GC_71,AMP(81))
      CALL VSS1_3(W(1,1),W(1,11),GC_81,MDL_MSD6,MDL_WSD6,W(1,7))
C     Amplitude(s) for diagram number 71
      CALL VSS1_0(W(1,9),W(1,3),W(1,7),GC_79,AMP(82))
C     Amplitude(s) for diagram number 72
      CALL VSS1_0(W(1,18),W(1,3),W(1,11),GC_79,AMP(83))
      CALL FFV1_1(W(1,13),W(1,1),GC_7,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 73
      CALL FFV1_0(W(1,6),W(1,11),W(1,8),GC_7,AMP(84))
      CALL VVV1P0_1(W(1,1),W(1,8),GC_6,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 74
      CALL FFV1_0(W(1,6),W(1,13),W(1,11),GC_7,AMP(85))
      CALL FFV1_2(W(1,16),W(1,1),GC_7,ZERO,ZERO,W(1,7))
C     Amplitude(s) for diagram number 75
      CALL FFV1_0(W(1,7),W(1,2),W(1,8),GC_7,AMP(86))
C     Amplitude(s) for diagram number 76
      CALL FFV1_0(W(1,16),W(1,2),W(1,11),GC_7,AMP(87))
C     Amplitude(s) for diagram number 77
      CALL VVVV1_0(W(1,1),W(1,5),W(1,8),W(1,9),GC_96,AMP(88))
      CALL VVVV3_0(W(1,1),W(1,5),W(1,8),W(1,9),GC_96,AMP(89))
      CALL VVVV4_0(W(1,1),W(1,5),W(1,8),W(1,9),GC_96,AMP(90))
C     Amplitude(s) for diagram number 78
      CALL VVV1_0(W(1,5),W(1,9),W(1,11),GC_6,AMP(91))
C     Amplitude(s) for diagram number 79
      CALL VVV1_0(W(1,5),W(1,8),W(1,18),GC_6,AMP(92))
      CALL VVSS1_3(W(1,1),W(1,5),W(1,3),GC_18,MDL_MSD3,MDL_WSD3,W(1,18)
     $ )
      CALL VVSS1_3(W(1,1),W(1,5),W(1,3),GC_18,MDL_MSD3,MDL_WSD3,W(1,8))
C     Amplitude(s) for diagram number 80
      CALL VSS1_0(W(1,9),W(1,4),W(1,18),GC_71,AMP(93))
      CALL VSS1_0(W(1,9),W(1,4),W(1,8),GC_71,AMP(94))
      CALL VVSS1_4(W(1,1),W(1,5),W(1,3),GC_21,MDL_MSD6,MDL_WSD6,W(1,8))
      CALL VVSS1_4(W(1,1),W(1,5),W(1,3),GC_21,MDL_MSD6,MDL_WSD6,W(1,18)
     $ )
C     Amplitude(s) for diagram number 81
      CALL VSS1_0(W(1,9),W(1,4),W(1,8),GC_73,AMP(95))
      CALL VSS1_0(W(1,9),W(1,4),W(1,18),GC_73,AMP(96))
      CALL VVSS1_4(W(1,1),W(1,5),W(1,4),GC_18,MDL_MSD3,MDL_WSD3,W(1,18)
     $ )
      CALL VVSS1_4(W(1,1),W(1,5),W(1,4),GC_18,MDL_MSD3,MDL_WSD3,W(1,8))
C     Amplitude(s) for diagram number 82
      CALL VSS1_0(W(1,9),W(1,18),W(1,3),GC_71,AMP(97))
      CALL VSS1_0(W(1,9),W(1,8),W(1,3),GC_71,AMP(98))
      CALL VVSS1_4(W(1,1),W(1,5),W(1,4),GC_21,MDL_MSD6,MDL_WSD6,W(1,8))
      CALL VVSS1_4(W(1,1),W(1,5),W(1,4),GC_21,MDL_MSD6,MDL_WSD6,W(1,18)
     $ )
C     Amplitude(s) for diagram number 83
      CALL VSS1_0(W(1,9),W(1,3),W(1,8),GC_79,AMP(99))
      CALL VSS1_0(W(1,9),W(1,3),W(1,18),GC_79,AMP(100))
      CALL VVSS1P0_1(W(1,1),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,18))
      CALL VVSS1P0_1(W(1,1),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,8))
C     Amplitude(s) for diagram number 84
      CALL FFV1_0(W(1,6),W(1,13),W(1,18),GC_7,AMP(101))
      CALL FFV1_0(W(1,6),W(1,13),W(1,8),GC_7,AMP(102))
C     Amplitude(s) for diagram number 85
      CALL FFV1_0(W(1,16),W(1,2),W(1,18),GC_7,AMP(103))
      CALL FFV1_0(W(1,16),W(1,2),W(1,8),GC_7,AMP(104))
C     Amplitude(s) for diagram number 86
      CALL VVV1_0(W(1,18),W(1,5),W(1,9),GC_6,AMP(105))
      CALL VVV1_0(W(1,8),W(1,5),W(1,9),GC_6,AMP(106))
C     Amplitude(s) for diagram number 87
      CALL VVV1_0(W(1,1),W(1,10),W(1,9),GC_6,AMP(107))
      CALL VVV1_0(W(1,1),W(1,17),W(1,9),GC_6,AMP(108))
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1)=+1D0/2D0*(-AMP(28)-AMP(29)-AMP(30)-AMP(31)-AMP(34)
     $ -AMP(35)-AMP(37)+IMAG1*AMP(40)-AMP(42)+IMAG1*AMP(45)-AMP(46)
     $ -AMP(47)-AMP(50)-IMAG1*AMP(52)-AMP(53)-AMP(64)-IMAG1*AMP(68)
     $ -AMP(69)-IMAG1*AMP(73)+IMAG1*AMP(87)+AMP(89)+AMP(90)+AMP(91)
     $ +AMP(92)-AMP(104)+IMAG1*AMP(106)+IMAG1*AMP(107))
      JAMP(2,1)=+1D0/2D0*(+1D0/3D0*AMP(46)+1D0/3D0*AMP(47)+1D0/3D0
     $ *AMP(48)+1D0/3D0*AMP(49)+1D0/3D0*AMP(54)+1D0/3D0*AMP(53)+1D0
     $ /3D0*AMP(55)+1D0/3D0*AMP(56)+1D0/3D0*AMP(57)+1D0/3D0*AMP(58)
     $ +1D0/3D0*AMP(63)+1D0/3D0*AMP(62))
      JAMP(3,1)=+1D0/2D0*(+1D0/3D0*AMP(14)+1D0/3D0*AMP(15)+1D0/3D0
     $ *AMP(16)+1D0/3D0*AMP(17)+1D0/3D0*AMP(32)+1D0/3D0*AMP(33)+1D0
     $ /3D0*AMP(34)+1D0/3D0*AMP(35)+1D0/3D0*AMP(102)+1D0/3D0*AMP(101)
     $ +1D0/3D0*AMP(104)+1D0/3D0*AMP(103))
      JAMP(4,1)=+1D0/2D0*(-AMP(10)-AMP(11)-AMP(12)-AMP(13)-AMP(14)
     $ -AMP(15)-AMP(18)-IMAG1*AMP(22)-AMP(23)-IMAG1*AMP(27)-AMP(57)
     $ -AMP(58)-AMP(59)+IMAG1*AMP(61)-AMP(63)-AMP(75)+IMAG1*AMP(78)
     $ -AMP(80)+IMAG1*AMP(83)-IMAG1*AMP(85)+AMP(89)+AMP(90)+AMP(91)
     $ +AMP(92)-AMP(101)-IMAG1*AMP(105)-IMAG1*AMP(108))
      JAMP(5,1)=+1D0/2D0*(+IMAG1*AMP(1)+AMP(3)+IMAG1*AMP(4)+IMAG1
     $ *AMP(8)+IMAG1*AMP(9)-AMP(48)-AMP(49)-AMP(51)+IMAG1*AMP(52)
     $ -AMP(54)-AMP(74)-AMP(76)-AMP(77)-IMAG1*AMP(78)-AMP(79)-AMP(81)
     $ -AMP(82)-IMAG1*AMP(83)+AMP(88)-AMP(90)-AMP(92)-AMP(98)-AMP(100)
     $ +IMAG1*AMP(108))
      JAMP(6,1)=+1D0/2D0*(-1D0/3D0*IMAG1*AMP(1)-1D0/3D0*IMAG1*AMP(2)
     $ +1D0/3D0*AMP(50)+1D0/3D0*AMP(51)+1D0/3D0*AMP(86))
      JAMP(7,1)=+1D0/2D0*(-1D0/3D0*IMAG1*AMP(4)-1D0/3D0*IMAG1*AMP(5)
     $ -1D0/3D0*IMAG1*AMP(6)-1D0/3D0*IMAG1*AMP(7)-1D0/3D0*IMAG1*AMP(8)
     $ -1D0/3D0*IMAG1*AMP(9)+1D0/3D0*AMP(10)+1D0/3D0*AMP(11)+1D0/3D0
     $ *AMP(12)+1D0/3D0*AMP(13)+1D0/3D0*AMP(18)+1D0/3D0*AMP(19)+1D0
     $ /3D0*AMP(20)+1D0/3D0*AMP(21)+1D0/3D0*AMP(23)+1D0/3D0*AMP(24)
     $ +1D0/3D0*AMP(25)+1D0/3D0*AMP(26)+1D0/3D0*AMP(74)+1D0/3D0*AMP(75)
     $ +1D0/3D0*AMP(76)+1D0/3D0*AMP(77)+1D0/3D0*AMP(79)+1D0/3D0*AMP(80)
     $ +1D0/3D0*AMP(81)+1D0/3D0*AMP(82)+1D0/3D0*AMP(94)+1D0/3D0*AMP(96)
     $ +1D0/3D0*AMP(98)+1D0/3D0*AMP(100))
      JAMP(8,1)=+1D0/2D0*(+IMAG1*AMP(2)-AMP(3)+IMAG1*AMP(5)+IMAG1
     $ *AMP(6)+IMAG1*AMP(7)-AMP(16)-AMP(17)-AMP(19)-AMP(20)-AMP(21)
     $ +IMAG1*AMP(22)-AMP(24)-AMP(25)-AMP(26)+IMAG1*AMP(27)-AMP(86)
     $ -IMAG1*AMP(87)-AMP(88)-AMP(89)-AMP(91)-AMP(94)-AMP(96)-AMP(103)
     $ +IMAG1*AMP(105))
      JAMP(9,1)=+1D0/2D0*(-IMAG1*AMP(2)+AMP(3)-IMAG1*AMP(5)-IMAG1
     $ *AMP(6)-IMAG1*AMP(7)-AMP(55)-AMP(56)-AMP(60)-IMAG1*AMP(61)
     $ -AMP(62)-AMP(65)-AMP(66)-AMP(67)+IMAG1*AMP(68)-AMP(70)-AMP(71)
     $ -AMP(72)+IMAG1*AMP(73)+AMP(88)-AMP(90)-AMP(92)-AMP(93)-AMP(95)
     $ -IMAG1*AMP(107))
      JAMP(10,1)=+1D0/2D0*(+1D0/3D0*IMAG1*AMP(4)+1D0/3D0*IMAG1*AMP(5)
     $ +1D0/3D0*IMAG1*AMP(6)+1D0/3D0*IMAG1*AMP(7)+1D0/3D0*IMAG1*AMP(8)
     $ +1D0/3D0*IMAG1*AMP(9)+1D0/3D0*AMP(28)+1D0/3D0*AMP(29)+1D0/3D0
     $ *AMP(30)+1D0/3D0*AMP(31)+1D0/3D0*AMP(36)+1D0/3D0*AMP(37)+1D0
     $ /3D0*AMP(38)+1D0/3D0*AMP(39)+1D0/3D0*AMP(41)+1D0/3D0*AMP(42)
     $ +1D0/3D0*AMP(43)+1D0/3D0*AMP(44)+1D0/3D0*AMP(64)+1D0/3D0*AMP(65)
     $ +1D0/3D0*AMP(66)+1D0/3D0*AMP(67)+1D0/3D0*AMP(69)+1D0/3D0*AMP(70)
     $ +1D0/3D0*AMP(71)+1D0/3D0*AMP(72)+1D0/3D0*AMP(93)+1D0/3D0*AMP(95)
     $ +1D0/3D0*AMP(97)+1D0/3D0*AMP(99))
      JAMP(11,1)=+1D0/2D0*(+1D0/3D0*IMAG1*AMP(1)+1D0/3D0*IMAG1*AMP(2)
     $ +1D0/3D0*AMP(59)+1D0/3D0*AMP(60)+1D0/3D0*AMP(84))
      JAMP(12,1)=+1D0/2D0*(-IMAG1*AMP(1)-AMP(3)-IMAG1*AMP(4)-IMAG1
     $ *AMP(8)-IMAG1*AMP(9)-AMP(32)-AMP(33)-AMP(36)-AMP(38)-AMP(39)
     $ -IMAG1*AMP(40)-AMP(41)-AMP(43)-AMP(44)-IMAG1*AMP(45)-AMP(84)
     $ +IMAG1*AMP(85)-AMP(88)-AMP(89)-AMP(91)-AMP(97)-AMP(99)-AMP(102)
     $ -IMAG1*AMP(106))

      MATRIX2 = 0.D0
      DO M = 1, NAMPSO
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX2(M,N))) THEN
              MATRIX2 = MATRIX2 + ZTEMP*DCONJG(JAMP(I,N))/DENOM(I)
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(5)=AMP2(5)+AMP(6)*DCONJG(AMP(6))
      AMP2(6)=AMP2(6)+AMP(7)*DCONJG(AMP(7))
      AMP2(7)=AMP2(7)+AMP(8)*DCONJG(AMP(8))
      AMP2(8)=AMP2(8)+AMP(9)*DCONJG(AMP(9))
      AMP2(9)=AMP2(9)+AMP(10)*DCONJG(AMP(10))
      AMP2(10)=AMP2(10)+AMP(11)*DCONJG(AMP(11))
      AMP2(11)=AMP2(11)+AMP(12)*DCONJG(AMP(12))
      AMP2(12)=AMP2(12)+AMP(13)*DCONJG(AMP(13))
      AMP2(15)=AMP2(15)+AMP(16)*DCONJG(AMP(16))
      AMP2(16)=AMP2(16)+AMP(17)*DCONJG(AMP(17))
      AMP2(13)=AMP2(13)+AMP(14)*DCONJG(AMP(14))
      AMP2(14)=AMP2(14)+AMP(15)*DCONJG(AMP(15))
      AMP2(18)=AMP2(18)+AMP(20)*DCONJG(AMP(20))
      AMP2(19)=AMP2(19)+AMP(21)*DCONJG(AMP(21))
      AMP2(20)=AMP2(20)+AMP(22)*DCONJG(AMP(22))
      AMP2(22)=AMP2(22)+AMP(25)*DCONJG(AMP(25))
      AMP2(23)=AMP2(23)+AMP(26)*DCONJG(AMP(26))
      AMP2(24)=AMP2(24)+AMP(27)*DCONJG(AMP(27))
      AMP2(25)=AMP2(25)+AMP(28)*DCONJG(AMP(28))
      AMP2(26)=AMP2(26)+AMP(29)*DCONJG(AMP(29))
      AMP2(27)=AMP2(27)+AMP(30)*DCONJG(AMP(30))
      AMP2(28)=AMP2(28)+AMP(31)*DCONJG(AMP(31))
      AMP2(31)=AMP2(31)+AMP(34)*DCONJG(AMP(34))
      AMP2(32)=AMP2(32)+AMP(35)*DCONJG(AMP(35))
      AMP2(29)=AMP2(29)+AMP(32)*DCONJG(AMP(32))
      AMP2(30)=AMP2(30)+AMP(33)*DCONJG(AMP(33))
      AMP2(34)=AMP2(34)+AMP(38)*DCONJG(AMP(38))
      AMP2(35)=AMP2(35)+AMP(39)*DCONJG(AMP(39))
      AMP2(36)=AMP2(36)+AMP(40)*DCONJG(AMP(40))
      AMP2(38)=AMP2(38)+AMP(43)*DCONJG(AMP(43))
      AMP2(39)=AMP2(39)+AMP(44)*DCONJG(AMP(44))
      AMP2(40)=AMP2(40)+AMP(45)*DCONJG(AMP(45))
      AMP2(49)=AMP2(49)+AMP(55)*DCONJG(AMP(55))
      AMP2(50)=AMP2(50)+AMP(56)*DCONJG(AMP(56))
      AMP2(51)=AMP2(51)+AMP(57)*DCONJG(AMP(57))
      AMP2(52)=AMP2(52)+AMP(58)*DCONJG(AMP(58))
      AMP2(53)=AMP2(53)+AMP(59)*DCONJG(AMP(59))
      AMP2(54)=AMP2(54)+AMP(60)*DCONJG(AMP(60))
      AMP2(55)=AMP2(55)+AMP(61)*DCONJG(AMP(61))
      AMP2(41)=AMP2(41)+AMP(46)*DCONJG(AMP(46))
      AMP2(42)=AMP2(42)+AMP(47)*DCONJG(AMP(47))
      AMP2(43)=AMP2(43)+AMP(48)*DCONJG(AMP(48))
      AMP2(44)=AMP2(44)+AMP(49)*DCONJG(AMP(49))
      AMP2(45)=AMP2(45)+AMP(50)*DCONJG(AMP(50))
      AMP2(46)=AMP2(46)+AMP(51)*DCONJG(AMP(51))
      AMP2(47)=AMP2(47)+AMP(52)*DCONJG(AMP(52))
      AMP2(58)=AMP2(58)+AMP(66)*DCONJG(AMP(66))
      AMP2(59)=AMP2(59)+AMP(67)*DCONJG(AMP(67))
      AMP2(60)=AMP2(60)+AMP(68)*DCONJG(AMP(68))
      AMP2(62)=AMP2(62)+AMP(71)*DCONJG(AMP(71))
      AMP2(63)=AMP2(63)+AMP(72)*DCONJG(AMP(72))
      AMP2(64)=AMP2(64)+AMP(73)*DCONJG(AMP(73))
      AMP2(66)=AMP2(66)+AMP(76)*DCONJG(AMP(76))
      AMP2(67)=AMP2(67)+AMP(77)*DCONJG(AMP(77))
      AMP2(68)=AMP2(68)+AMP(78)*DCONJG(AMP(78))
      AMP2(70)=AMP2(70)+AMP(81)*DCONJG(AMP(81))
      AMP2(71)=AMP2(71)+AMP(82)*DCONJG(AMP(82))
      AMP2(72)=AMP2(72)+AMP(83)*DCONJG(AMP(83))
      AMP2(75)=AMP2(75)+AMP(86)*DCONJG(AMP(86))
      AMP2(76)=AMP2(76)+AMP(87)*DCONJG(AMP(87))
      AMP2(73)=AMP2(73)+AMP(84)*DCONJG(AMP(84))
      AMP2(74)=AMP2(74)+AMP(85)*DCONJG(AMP(85))
      AMP2(78)=AMP2(78)+AMP(91)*DCONJG(AMP(91))
      AMP2(79)=AMP2(79)+AMP(92)*DCONJG(AMP(92))
      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX2(M,N))) THEN
              JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      END

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX2(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS2/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS2
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)+AMPSPLITORDERS(ORDERI
     $NDEXB,I)
      ENDDO
      SQSOINDEX2=SOINDEX_FOR_SQUARED_ORDERS2(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS2(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS2/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS2 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS2'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN2(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX2(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS2/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_SQUARED_ORDERS_FOR_SOIN'
     $ //'DEX2'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX2(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS2/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX2'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS2(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS2/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS2 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS2'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

