      SUBROUTINE SMATRIX1(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.4.3, 2016-08-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > b1 b1~ b b~ WEIGHTED<=4 @3
C     
      USE DISCRETESAMPLER
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=183)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=158)
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     global (due to reading writting) 
C     
      LOGICAL GOODHEL(NCOMB,2)
      INTEGER NTRY(2)
      COMMON/BLOCK_GOODHEL/NTRY,GOODHEL
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      INTEGER ISHEL(2)
      REAL*8 T,MATRIX1
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER NGOOD(2), IGOOD(NCOMB,2)
      INTEGER JHEL(2), J, JJ
      INTEGER THIS_NTRY(2)
      SAVE THIS_NTRY
      DATA THIS_NTRY /0,0/
C     This is just to temporarily store the reference grid for
C      helicity of the DiscreteSampler so as to obtain its number of
C      entries with ref_helicity_grid%n_tot_entries
      TYPE(SAMPLEDDIMENSION) REF_HELICITY_GRID
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2

      CHARACTER*101         HEL_BUFF
      COMMON/TO_HELICITY/  HEL_BUFF

      INTEGER IMIRROR
      COMMON/TO_MIRROR/ IMIRROR

      REAL*8 POL(2)
      COMMON/TO_POLARIZATION/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      DATA XTRY, XREJ /0,0/
      DATA NGOOD /0,0/
      DATA ISHEL/0,0/
      SAVE YFRAC, IGOOD, JHEL
      DATA (NHEL(I,   1),I=1,6) /-1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,   5),I=1,6) /-1, 1, 0, 0,-1, 1/
      DATA (NHEL(I,   6),I=1,6) /-1, 1, 0, 0,-1,-1/
      DATA (NHEL(I,   7),I=1,6) /-1, 1, 0, 0, 1, 1/
      DATA (NHEL(I,   8),I=1,6) /-1, 1, 0, 0, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 0, 0,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 0, 0,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 0, 0, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 0, 0, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1, 1, 0, 0,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1, 1, 0, 0,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1, 1, 0, 0, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1, 1, 0, 0, 1,-1/
      DATA IDEN/256/

C     To be able to control when the matrix<i> subroutine can add
C      entries to the grid for the MC over helicity configuration
      LOGICAL ALLOW_HELICITY_GRID_ENTRIES
      COMMON/TO_ALLOW_HELICITY_GRID_ENTRIES/ALLOW_HELICITY_GRID_ENTRIES

C     ----------
C     BEGIN CODE
C     ----------
      NTRY(IMIRROR)=NTRY(IMIRROR)+1
      THIS_NTRY(IMIRROR) = THIS_NTRY(IMIRROR)+1
      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
        JAMP2(0)=12
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
      ENDIF
      ANS = 0D0
      WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL)
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO

        !   If the helicity grid status is 0, this means that it is not yet initialized.
        !   If HEL_PICKED==-1, this means that calls to other matrix<i> where in initialization mode as well for the helicity.
      IF ((ISHEL(IMIRROR).EQ.0.AND.ISUM_HEL.EQ.0).OR.(DS_GET_DIM_STATUS
     $('Helicity').EQ.0).OR.(HEL_PICKED.EQ.-1)) THEN
        DO I=1,NCOMB
          IF (GOODHEL(I,IMIRROR) .OR. NTRY(IMIRROR).LE.MAXTRIES.OR.(ISU
     $M_HEL.NE.0).OR.THIS_NTRY(IMIRROR).LE.2) THEN
            T=MATRIX1(P ,NHEL(1,I),JC(1))
            DO JJ=1,NINCOMING
              IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))
     $         )) THEN
                T=T*ABS(POL(JJ))
              ELSE IF(POL(JJ).NE.1D0)THEN
                T=T*(2D0-ABS(POL(JJ)))
              ENDIF
            ENDDO
            IF (ISUM_HEL.NE.0.AND.DS_GET_DIM_STATUS('Helicity')
     $       .EQ.0.AND.ALLOW_HELICITY_GRID_ENTRIES) THEN
              CALL DS_ADD_ENTRY('Helicity',I,T)
            ENDIF
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        IF(NTRY(IMIRROR).EQ.(MAXTRIES+1)) THEN
          CALL RESET_CUMULATIVE_VARIABLE()  ! avoid biais of the initialization
        ENDIF
        IF (ISUM_HEL.NE.0) THEN
            !         We set HEL_PICKED to -1 here so that later on, the call to DS_add_point in dsample.f does not add anything to the grid since it was already done here.
          HEL_PICKED = -1
            !         For safety, hardset the helicity sampling jacobian to 0.0d0 to make sure it is not .
          HEL_JACOBIAN   = 1.0D0
            !         We don't want to re-update the helicity grid if it was already updated by another matrix<i>, so we make sure that the reference grid is empty.
          REF_HELICITY_GRID = DS_GET_DIMENSION(REF_GRID,'Helicity')
          IF((DS_GET_DIM_STATUS('Helicity').EQ.1).AND.(REF_HELICITY_GRI
     $D%N_TOT_ENTRIES.EQ.0)) THEN
              !           If we finished the initialization we can update the grid so as to start sampling over it.
              !           However the grid will now be filled by dsample with different kind of weights (including pdf, flux, etc...) so by setting the grid_mode of the reference grid to 'initialization' we make sure it will be overwritten (as opposed to 'combined') by the running grid at the next update.
            CALL DS_UPDATE_GRID('Helicity')
            CALL DS_SET_GRID_MODE('Helicity','init')
          ENDIF
        ELSE
          JHEL(IMIRROR) = 1
          IF(NTRY(IMIRROR).LE.MAXTRIES.OR.THIS_NTRY(IMIRROR).LE.2)THEN
            DO I=1,NCOMB
              IF (.NOT.GOODHEL(I,IMIRROR) .AND. (DABS(TS(I)).GT.ANS
     $         *LIMHEL/NCOMB)) THEN
                GOODHEL(I,IMIRROR)=.TRUE.
                NGOOD(IMIRROR) = NGOOD(IMIRROR) +1
                IGOOD(NGOOD(IMIRROR),IMIRROR) = I
                PRINT *,'Added good helicity ',I,TS(I)*NCOMB/ANS,' in'
     $           //' event ',NTRY(IMIRROR), 'local:',THIS_NTRY(IMIRROR)
              ENDIF
            ENDDO
          ENDIF
          IF(NTRY(IMIRROR).EQ.MAXTRIES)THEN
            ISHEL(IMIRROR)=MIN(ISUM_HEL,NGOOD(IMIRROR))
          ENDIF
        ENDIF
      ELSE  ! random helicity 
C       The helicity configuration was chosen already by genps and put
C        in a common block defined in genps.inc.
        I = HEL_PICKED

        T=MATRIX1(P ,NHEL(1,I),JC(1))

        DO JJ=1,NINCOMING
          IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))
          ELSE IF(POL(JJ).NE.1D0)THEN
            T=T*(2D0-ABS(POL(JJ)))
          ENDIF
        ENDDO
C       Always one helicity at a time
        ANS = T
C       Include the Jacobian from helicity sampling
        ANS = ANS * HEL_JACOBIAN

        WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
      ENDIF
      IF (ANS.NE.0D0.AND.(ISUM_HEL .NE. 1.OR.HEL_PICKED.EQ.-1)) THEN
        CALL RANMAR(R)
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(R.LT.SUMHEL)THEN
            WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(1))/XTOT
        ELSE
          ANS=0D0
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX1(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.4.3, 2016-08-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > b1 b1~ b b~ WEIGHTED<=4 @3
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=183)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=25, NCOLOR=12)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX1
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/3/
      DATA (CF(I,  1),I=  1,  6) /   48,   16,   16,    6,    0,   16/
      DATA (CF(I,  1),I=  7, 12) /   -2,    0,   -6,   -2,   -2,    6/
C     1 T(1,2,3,4) T(5,6)
      DATA DENOM(2)/3/
      DATA (CF(I,  2),I=  1,  6) /   16,   48,    6,   16,   16,    0/
      DATA (CF(I,  2),I=  7, 12) /    0,   -2,   -2,   -6,    6,   -2/
C     1 T(1,2,3,6) T(5,4)
      DATA DENOM(3)/3/
      DATA (CF(I,  3),I=  1,  6) /   16,    6,   48,   16,   -2,    0/
      DATA (CF(I,  3),I=  7, 12) /    0,   16,   -2,    6,   -6,   -2/
C     1 T(1,2,5,4) T(3,6)
      DATA DENOM(4)/3/
      DATA (CF(I,  4),I=  1,  6) /    6,   16,   16,   48,    0,   -2/
      DATA (CF(I,  4),I=  7, 12) /   16,    0,    6,   -2,   -2,   -6/
C     1 T(1,2,5,6) T(3,4)
      DATA DENOM(5)/3/
      DATA (CF(I,  5),I=  1,  6) /    0,   16,   -2,    0,   48,   16/
      DATA (CF(I,  5),I=  7, 12) /   16,    6,    0,   -2,   16,    0/
C     1 T(1,3,4) T(2,5,6)
      DATA DENOM(6)/3/
      DATA (CF(I,  6),I=  1,  6) /   16,    0,    0,   -2,   16,   48/
      DATA (CF(I,  6),I=  7, 12) /    6,   16,   -2,    0,    0,   16/
C     1 T(1,3,6) T(2,5,4)
      DATA DENOM(7)/3/
      DATA (CF(I,  7),I=  1,  6) /   -2,    0,    0,   16,   16,    6/
      DATA (CF(I,  7),I=  7, 12) /   48,   16,   16,    0,    0,   -2/
C     1 T(1,5,4) T(2,3,6)
      DATA DENOM(8)/3/
      DATA (CF(I,  8),I=  1,  6) /    0,   -2,   16,    0,    6,   16/
      DATA (CF(I,  8),I=  7, 12) /   16,   48,    0,   16,   -2,    0/
C     1 T(1,5,6) T(2,3,4)
      DATA DENOM(9)/3/
      DATA (CF(I,  9),I=  1,  6) /   -6,   -2,   -2,    6,    0,   -2/
      DATA (CF(I,  9),I=  7, 12) /   16,    0,   48,   16,   16,    6/
C     1 T(2,1,3,4) T(5,6)
      DATA DENOM(10)/3/
      DATA (CF(I, 10),I=  1,  6) /   -2,   -6,    6,   -2,   -2,    0/
      DATA (CF(I, 10),I=  7, 12) /    0,   16,   16,   48,    6,   16/
C     1 T(2,1,3,6) T(5,4)
      DATA DENOM(11)/3/
      DATA (CF(I, 11),I=  1,  6) /   -2,    6,   -6,   -2,   16,    0/
      DATA (CF(I, 11),I=  7, 12) /    0,   -2,   16,    6,   48,   16/
C     1 T(2,1,5,4) T(3,6)
      DATA DENOM(12)/3/
      DATA (CF(I, 12),I=  1,  6) /    6,   -2,   -2,   -6,    0,   16/
      DATA (CF(I, 12),I=  7, 12) /   -2,    0,    6,   16,   16,   48/
C     1 T(2,1,5,6) T(3,4)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL SXXXXX(P(0,4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_MB,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MB,NHEL(6),-1*IC(6),W(1,6))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_6,ZERO,ZERO,W(1,7))
      CALL VSS1P0_1(W(1,4),W(1,3),GC_71,ZERO,ZERO,W(1,8))
      CALL FFV1_1(W(1,5),W(1,7),GC_7,MDL_MB,ZERO,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,6),W(1,9),W(1,8),GC_7,AMP(1))
      CALL FFV1_2(W(1,6),W(1,7),GC_7,MDL_MB,ZERO,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,10),W(1,5),W(1,8),GC_7,AMP(2))
      CALL FFV1P0_3(W(1,6),W(1,5),GC_7,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,7),W(1,8),W(1,11),GC_6,AMP(3))
      CALL FFS1_2_2(W(1,6),W(1,3),GC_108,GC_513,MDL_MGO,MDL_WGO,W(1,12)
     $ )
      CALL VSS1_3(W(1,7),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,13))
C     Amplitude(s) for diagram number 4
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,13),GC_513,GC_108,AMP(4))
      CALL VSS1_3(W(1,7),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,14))
C     Amplitude(s) for diagram number 5
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,14),GC_533,GC_528,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFS1_2_0(W(1,12),W(1,9),W(1,4),GC_513,GC_108,AMP(6))
      CALL FFS1_2_1(W(1,5),W(1,4),GC_513,GC_108,MDL_MGO,MDL_WGO,W(1,9))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,12),W(1,9),W(1,7),GC_8,AMP(7))
      CALL VSS1_2(W(1,7),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,15))
C     Amplitude(s) for diagram number 8
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,15),GC_108,GC_513,AMP(8))
      CALL VSS1_3(W(1,7),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,16))
C     Amplitude(s) for diagram number 9
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,16),GC_528,GC_533,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFS1_2_0(W(1,10),W(1,9),W(1,3),GC_108,GC_513,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL VVSS1_0(W(1,7),W(1,11),W(1,4),W(1,3),GC_18,AMP(11))
      CALL VVSS1_0(W(1,7),W(1,11),W(1,4),W(1,3),GC_18,AMP(12))
C     Amplitude(s) for diagram number 12
      CALL VSS1_0(W(1,11),W(1,4),W(1,15),GC_71,AMP(13))
C     Amplitude(s) for diagram number 13
      CALL VSS1_0(W(1,11),W(1,4),W(1,16),GC_73,AMP(14))
C     Amplitude(s) for diagram number 14
      CALL VSS1_0(W(1,11),W(1,13),W(1,3),GC_71,AMP(15))
C     Amplitude(s) for diagram number 15
      CALL VSS1_0(W(1,11),W(1,3),W(1,14),GC_79,AMP(16))
      CALL VSS1_2(W(1,1),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,14))
      CALL VSS1_3(W(1,2),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,13))
      CALL FFS1_2_2(W(1,6),W(1,14),GC_108,GC_513,MDL_MGO,MDL_WGO,W(1
     $ ,16))
C     Amplitude(s) for diagram number 16
      CALL FFS1_2_0(W(1,16),W(1,5),W(1,13),GC_513,GC_108,AMP(17))
      CALL VSS1_3(W(1,2),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,15))
C     Amplitude(s) for diagram number 17
      CALL FFS1_2_0(W(1,16),W(1,5),W(1,15),GC_533,GC_528,AMP(18))
      CALL VSS1_3(W(1,1),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,7))
      CALL FFS1_2_2(W(1,6),W(1,7),GC_528,GC_533,MDL_MGO,MDL_WGO,W(1,10)
     $ )
C     Amplitude(s) for diagram number 18
      CALL FFS1_2_0(W(1,10),W(1,5),W(1,13),GC_513,GC_108,AMP(19))
C     Amplitude(s) for diagram number 19
      CALL FFS1_2_0(W(1,10),W(1,5),W(1,15),GC_533,GC_528,AMP(20))
C     Amplitude(s) for diagram number 20
      CALL VSS1_0(W(1,11),W(1,13),W(1,14),GC_71,AMP(21))
C     Amplitude(s) for diagram number 21
      CALL VSS1_0(W(1,11),W(1,14),W(1,15),GC_79,AMP(22))
C     Amplitude(s) for diagram number 22
      CALL VSS1_0(W(1,11),W(1,13),W(1,7),GC_73,AMP(23))
C     Amplitude(s) for diagram number 23
      CALL VSS1_0(W(1,11),W(1,15),W(1,7),GC_81,AMP(24))
      CALL FFV1_1(W(1,5),W(1,2),GC_7,MDL_MB,ZERO,W(1,17))
      CALL VSS1P0_1(W(1,4),W(1,14),GC_71,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 24
      CALL FFV1_0(W(1,6),W(1,17),W(1,18),GC_7,AMP(25))
C     Amplitude(s) for diagram number 25
      CALL FFS1_2_0(W(1,16),W(1,17),W(1,4),GC_513,GC_108,AMP(26))
      CALL VSS1P0_1(W(1,4),W(1,7),GC_73,ZERO,ZERO,W(1,19))
C     Amplitude(s) for diagram number 26
      CALL FFV1_0(W(1,6),W(1,17),W(1,19),GC_7,AMP(27))
C     Amplitude(s) for diagram number 27
      CALL FFS1_2_0(W(1,10),W(1,17),W(1,4),GC_513,GC_108,AMP(28))
      CALL FFV1_2(W(1,6),W(1,2),GC_7,MDL_MB,ZERO,W(1,20))
C     Amplitude(s) for diagram number 28
      CALL FFV1_0(W(1,20),W(1,5),W(1,18),GC_7,AMP(29))
C     Amplitude(s) for diagram number 29
      CALL FFV1_0(W(1,20),W(1,5),W(1,19),GC_7,AMP(30))
C     Amplitude(s) for diagram number 30
      CALL FFS1_2_0(W(1,20),W(1,9),W(1,14),GC_108,GC_513,AMP(31))
C     Amplitude(s) for diagram number 31
      CALL FFS1_2_0(W(1,20),W(1,9),W(1,7),GC_528,GC_533,AMP(32))
      CALL VSS1_2(W(1,2),W(1,14),GC_71,MDL_MSD3,MDL_WSD3,W(1,21))
C     Amplitude(s) for diagram number 32
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,21),GC_108,GC_513,AMP(33))
      CALL VSS1_3(W(1,2),W(1,14),GC_79,MDL_MSD6,MDL_WSD6,W(1,22))
C     Amplitude(s) for diagram number 33
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,22),GC_528,GC_533,AMP(34))
C     Amplitude(s) for diagram number 34
      CALL FFV1_0(W(1,16),W(1,9),W(1,2),GC_8,AMP(35))
      CALL VSS1_2(W(1,2),W(1,7),GC_73,MDL_MSD3,MDL_WSD3,W(1,16))
C     Amplitude(s) for diagram number 35
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,16),GC_108,GC_513,AMP(36))
      CALL VSS1_2(W(1,2),W(1,7),GC_81,MDL_MSD6,MDL_WSD6,W(1,23))
C     Amplitude(s) for diagram number 36
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,23),GC_528,GC_533,AMP(37))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,10),W(1,9),W(1,2),GC_8,AMP(38))
C     Amplitude(s) for diagram number 38
      CALL VVSS1_0(W(1,2),W(1,11),W(1,4),W(1,14),GC_18,AMP(39))
      CALL VVSS1_0(W(1,2),W(1,11),W(1,4),W(1,14),GC_18,AMP(40))
C     Amplitude(s) for diagram number 39
      CALL VSS1_0(W(1,11),W(1,4),W(1,21),GC_71,AMP(41))
C     Amplitude(s) for diagram number 40
      CALL VSS1_0(W(1,11),W(1,4),W(1,22),GC_73,AMP(42))
C     Amplitude(s) for diagram number 41
      CALL VVV1_0(W(1,2),W(1,11),W(1,18),GC_6,AMP(43))
C     Amplitude(s) for diagram number 42
      CALL VVSS1_0(W(1,2),W(1,11),W(1,4),W(1,7),GC_21,AMP(44))
      CALL VVSS1_0(W(1,2),W(1,11),W(1,4),W(1,7),GC_21,AMP(45))
C     Amplitude(s) for diagram number 43
      CALL VSS1_0(W(1,11),W(1,4),W(1,16),GC_71,AMP(46))
C     Amplitude(s) for diagram number 44
      CALL VSS1_0(W(1,11),W(1,4),W(1,23),GC_73,AMP(47))
C     Amplitude(s) for diagram number 45
      CALL VVV1_0(W(1,2),W(1,11),W(1,19),GC_6,AMP(48))
      CALL VSS1_3(W(1,1),W(1,4),GC_71,MDL_MSD3,MDL_WSD3,W(1,19))
      CALL VSS1_2(W(1,2),W(1,3),GC_71,MDL_MSD3,MDL_WSD3,W(1,23))
      CALL FFS1_2_1(W(1,5),W(1,19),GC_513,GC_108,MDL_MGO,MDL_WGO,W(1
     $ ,16))
C     Amplitude(s) for diagram number 46
      CALL FFS1_2_0(W(1,6),W(1,16),W(1,23),GC_108,GC_513,AMP(49))
      CALL VSS1_3(W(1,2),W(1,3),GC_79,MDL_MSD6,MDL_WSD6,W(1,7))
C     Amplitude(s) for diagram number 47
      CALL FFS1_2_0(W(1,6),W(1,16),W(1,7),GC_528,GC_533,AMP(50))
      CALL VSS1_3(W(1,1),W(1,4),GC_73,MDL_MSD6,MDL_WSD6,W(1,18))
      CALL FFS1_2_1(W(1,5),W(1,18),GC_533,GC_528,MDL_MGO,MDL_WGO,W(1
     $ ,22))
C     Amplitude(s) for diagram number 48
      CALL FFS1_2_0(W(1,6),W(1,22),W(1,23),GC_108,GC_513,AMP(51))
C     Amplitude(s) for diagram number 49
      CALL FFS1_2_0(W(1,6),W(1,22),W(1,7),GC_528,GC_533,AMP(52))
C     Amplitude(s) for diagram number 50
      CALL VSS1_0(W(1,11),W(1,19),W(1,23),GC_71,AMP(53))
C     Amplitude(s) for diagram number 51
      CALL VSS1_0(W(1,11),W(1,19),W(1,7),GC_73,AMP(54))
C     Amplitude(s) for diagram number 52
      CALL VSS1_0(W(1,11),W(1,23),W(1,18),GC_79,AMP(55))
C     Amplitude(s) for diagram number 53
      CALL VSS1_0(W(1,11),W(1,18),W(1,7),GC_81,AMP(56))
      CALL VSS1P0_1(W(1,19),W(1,3),GC_71,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 54
      CALL FFV1_0(W(1,6),W(1,17),W(1,21),GC_7,AMP(57))
      CALL VSS1P0_1(W(1,3),W(1,18),GC_79,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 55
      CALL FFV1_0(W(1,6),W(1,17),W(1,14),GC_7,AMP(58))
C     Amplitude(s) for diagram number 56
      CALL FFS1_2_0(W(1,12),W(1,17),W(1,19),GC_513,GC_108,AMP(59))
C     Amplitude(s) for diagram number 57
      CALL FFS1_2_0(W(1,12),W(1,17),W(1,18),GC_533,GC_528,AMP(60))
C     Amplitude(s) for diagram number 58
      CALL FFV1_0(W(1,20),W(1,5),W(1,21),GC_7,AMP(61))
C     Amplitude(s) for diagram number 59
      CALL FFS1_2_0(W(1,20),W(1,16),W(1,3),GC_108,GC_513,AMP(62))
C     Amplitude(s) for diagram number 60
      CALL FFV1_0(W(1,20),W(1,5),W(1,14),GC_7,AMP(63))
C     Amplitude(s) for diagram number 61
      CALL FFS1_2_0(W(1,20),W(1,22),W(1,3),GC_108,GC_513,AMP(64))
      CALL VSS1_3(W(1,2),W(1,19),GC_71,MDL_MSD3,MDL_WSD3,W(1,10))
C     Amplitude(s) for diagram number 62
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,10),GC_513,GC_108,AMP(65))
      CALL VSS1_3(W(1,2),W(1,19),GC_73,MDL_MSD6,MDL_WSD6,W(1,24))
C     Amplitude(s) for diagram number 63
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,24),GC_533,GC_528,AMP(66))
C     Amplitude(s) for diagram number 64
      CALL FFV1_0(W(1,12),W(1,16),W(1,2),GC_8,AMP(67))
      CALL VSS1_2(W(1,2),W(1,18),GC_79,MDL_MSD3,MDL_WSD3,W(1,16))
C     Amplitude(s) for diagram number 65
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,16),GC_513,GC_108,AMP(68))
      CALL VSS1_3(W(1,2),W(1,18),GC_81,MDL_MSD6,MDL_WSD6,W(1,25))
C     Amplitude(s) for diagram number 66
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,25),GC_533,GC_528,AMP(69))
C     Amplitude(s) for diagram number 67
      CALL FFV1_0(W(1,12),W(1,22),W(1,2),GC_8,AMP(70))
C     Amplitude(s) for diagram number 68
      CALL VVSS1_0(W(1,2),W(1,11),W(1,19),W(1,3),GC_18,AMP(71))
      CALL VVSS1_0(W(1,2),W(1,11),W(1,19),W(1,3),GC_18,AMP(72))
C     Amplitude(s) for diagram number 69
      CALL VSS1_0(W(1,11),W(1,10),W(1,3),GC_71,AMP(73))
C     Amplitude(s) for diagram number 70
      CALL VSS1_0(W(1,11),W(1,3),W(1,24),GC_79,AMP(74))
C     Amplitude(s) for diagram number 71
      CALL VVV1_0(W(1,2),W(1,11),W(1,21),GC_6,AMP(75))
C     Amplitude(s) for diagram number 72
      CALL VVSS1_0(W(1,2),W(1,11),W(1,3),W(1,18),GC_21,AMP(76))
      CALL VVSS1_0(W(1,2),W(1,11),W(1,3),W(1,18),GC_21,AMP(77))
C     Amplitude(s) for diagram number 73
      CALL VSS1_0(W(1,11),W(1,16),W(1,3),GC_71,AMP(78))
C     Amplitude(s) for diagram number 74
      CALL VSS1_0(W(1,11),W(1,3),W(1,25),GC_79,AMP(79))
C     Amplitude(s) for diagram number 75
      CALL VVV1_0(W(1,2),W(1,11),W(1,14),GC_6,AMP(80))
      CALL FFV1_1(W(1,5),W(1,1),GC_7,MDL_MB,ZERO,W(1,14))
      CALL FFS1_2_1(W(1,14),W(1,4),GC_513,GC_108,MDL_MGO,MDL_WGO,W(1
     $ ,25))
C     Amplitude(s) for diagram number 76
      CALL FFS1_2_0(W(1,6),W(1,25),W(1,23),GC_108,GC_513,AMP(81))
      CALL FFV1P0_3(W(1,6),W(1,14),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 77
      CALL VSS1_0(W(1,16),W(1,4),W(1,23),GC_71,AMP(82))
C     Amplitude(s) for diagram number 78
      CALL FFS1_2_0(W(1,6),W(1,25),W(1,7),GC_528,GC_533,AMP(83))
C     Amplitude(s) for diagram number 79
      CALL VSS1_0(W(1,16),W(1,4),W(1,7),GC_73,AMP(84))
C     Amplitude(s) for diagram number 80
      CALL VSS1_0(W(1,16),W(1,13),W(1,3),GC_71,AMP(85))
C     Amplitude(s) for diagram number 81
      CALL VSS1_0(W(1,16),W(1,3),W(1,15),GC_79,AMP(86))
C     Amplitude(s) for diagram number 82
      CALL FFS1_2_0(W(1,12),W(1,14),W(1,13),GC_513,GC_108,AMP(87))
C     Amplitude(s) for diagram number 83
      CALL FFS1_2_0(W(1,12),W(1,14),W(1,15),GC_533,GC_528,AMP(88))
C     Amplitude(s) for diagram number 84
      CALL FFS1_2_0(W(1,20),W(1,25),W(1,3),GC_108,GC_513,AMP(89))
C     Amplitude(s) for diagram number 85
      CALL FFV1_0(W(1,20),W(1,14),W(1,8),GC_7,AMP(90))
      CALL FFV1_1(W(1,14),W(1,2),GC_7,MDL_MB,ZERO,W(1,18))
C     Amplitude(s) for diagram number 86
      CALL FFV1_0(W(1,6),W(1,18),W(1,8),GC_7,AMP(91))
C     Amplitude(s) for diagram number 87
      CALL VVV1_0(W(1,2),W(1,8),W(1,16),GC_6,AMP(92))
C     Amplitude(s) for diagram number 88
      CALL FFS1_2_0(W(1,12),W(1,18),W(1,4),GC_513,GC_108,AMP(93))
C     Amplitude(s) for diagram number 89
      CALL FFV1_0(W(1,12),W(1,25),W(1,2),GC_8,AMP(94))
      CALL VVSS1P0_1(W(1,2),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,25))
      CALL VVSS1P0_1(W(1,2),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 90
      CALL FFV1_0(W(1,6),W(1,14),W(1,25),GC_7,AMP(95))
      CALL FFV1_0(W(1,6),W(1,14),W(1,18),GC_7,AMP(96))
      CALL FFV1_2(W(1,6),W(1,1),GC_7,MDL_MB,ZERO,W(1,14))
      CALL FFV1P0_3(W(1,14),W(1,5),GC_7,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 91
      CALL VSS1_0(W(1,16),W(1,4),W(1,23),GC_71,AMP(97))
C     Amplitude(s) for diagram number 92
      CALL VSS1_0(W(1,16),W(1,4),W(1,7),GC_73,AMP(98))
C     Amplitude(s) for diagram number 93
      CALL FFS1_2_0(W(1,14),W(1,9),W(1,23),GC_108,GC_513,AMP(99))
C     Amplitude(s) for diagram number 94
      CALL FFS1_2_0(W(1,14),W(1,9),W(1,7),GC_528,GC_533,AMP(100))
      CALL FFS1_2_2(W(1,14),W(1,3),GC_108,GC_513,MDL_MGO,MDL_WGO,W(1
     $ ,21))
C     Amplitude(s) for diagram number 95
      CALL FFS1_2_0(W(1,21),W(1,5),W(1,13),GC_513,GC_108,AMP(101))
C     Amplitude(s) for diagram number 96
      CALL VSS1_0(W(1,16),W(1,13),W(1,3),GC_71,AMP(102))
C     Amplitude(s) for diagram number 97
      CALL FFS1_2_0(W(1,21),W(1,5),W(1,15),GC_533,GC_528,AMP(103))
C     Amplitude(s) for diagram number 98
      CALL VSS1_0(W(1,16),W(1,3),W(1,15),GC_79,AMP(104))
C     Amplitude(s) for diagram number 99
      CALL FFS1_2_0(W(1,21),W(1,17),W(1,4),GC_513,GC_108,AMP(105))
C     Amplitude(s) for diagram number 100
      CALL FFV1_0(W(1,14),W(1,17),W(1,8),GC_7,AMP(106))
      CALL FFV1_2(W(1,14),W(1,2),GC_7,MDL_MB,ZERO,W(1,24))
C     Amplitude(s) for diagram number 101
      CALL FFV1_0(W(1,24),W(1,5),W(1,8),GC_7,AMP(107))
C     Amplitude(s) for diagram number 102
      CALL VVV1_0(W(1,2),W(1,8),W(1,16),GC_6,AMP(108))
C     Amplitude(s) for diagram number 103
      CALL FFS1_2_0(W(1,24),W(1,9),W(1,3),GC_108,GC_513,AMP(109))
C     Amplitude(s) for diagram number 104
      CALL FFV1_0(W(1,21),W(1,9),W(1,2),GC_8,AMP(110))
C     Amplitude(s) for diagram number 105
      CALL FFV1_0(W(1,14),W(1,5),W(1,25),GC_7,AMP(111))
      CALL FFV1_0(W(1,14),W(1,5),W(1,18),GC_7,AMP(112))
      CALL VSS1_2(W(1,1),W(1,23),GC_71,MDL_MSD3,MDL_WSD3,W(1,14))
C     Amplitude(s) for diagram number 106
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,14),GC_108,GC_513,AMP(113))
      CALL VSS1_3(W(1,1),W(1,23),GC_79,MDL_MSD6,MDL_WSD6,W(1,21))
C     Amplitude(s) for diagram number 107
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,21),GC_528,GC_533,AMP(114))
      CALL FFV1_1(W(1,9),W(1,1),GC_8,MDL_MGO,MDL_WGO,W(1,24))
C     Amplitude(s) for diagram number 108
      CALL FFS1_2_0(W(1,6),W(1,24),W(1,23),GC_108,GC_513,AMP(115))
      CALL VSS1_2(W(1,1),W(1,7),GC_73,MDL_MSD3,MDL_WSD3,W(1,16))
C     Amplitude(s) for diagram number 109
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,16),GC_108,GC_513,AMP(116))
      CALL VSS1_2(W(1,1),W(1,7),GC_81,MDL_MSD6,MDL_WSD6,W(1,10))
C     Amplitude(s) for diagram number 110
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,10),GC_528,GC_533,AMP(117))
C     Amplitude(s) for diagram number 111
      CALL FFS1_2_0(W(1,6),W(1,24),W(1,7),GC_528,GC_533,AMP(118))
C     Amplitude(s) for diagram number 112
      CALL VVSS1_0(W(1,1),W(1,11),W(1,4),W(1,23),GC_18,AMP(119))
      CALL VVSS1_0(W(1,1),W(1,11),W(1,4),W(1,23),GC_18,AMP(120))
C     Amplitude(s) for diagram number 113
      CALL VSS1_0(W(1,11),W(1,4),W(1,14),GC_71,AMP(121))
C     Amplitude(s) for diagram number 114
      CALL VSS1_0(W(1,11),W(1,4),W(1,21),GC_73,AMP(122))
      CALL VVV1P0_1(W(1,1),W(1,11),GC_6,ZERO,ZERO,W(1,21))
C     Amplitude(s) for diagram number 115
      CALL VSS1_0(W(1,21),W(1,4),W(1,23),GC_71,AMP(123))
C     Amplitude(s) for diagram number 116
      CALL VVSS1_0(W(1,1),W(1,11),W(1,4),W(1,7),GC_21,AMP(124))
      CALL VVSS1_0(W(1,1),W(1,11),W(1,4),W(1,7),GC_21,AMP(125))
C     Amplitude(s) for diagram number 117
      CALL VSS1_0(W(1,11),W(1,4),W(1,16),GC_71,AMP(126))
C     Amplitude(s) for diagram number 118
      CALL VSS1_0(W(1,11),W(1,4),W(1,10),GC_73,AMP(127))
C     Amplitude(s) for diagram number 119
      CALL VSS1_0(W(1,21),W(1,4),W(1,7),GC_73,AMP(128))
      CALL VSS1_3(W(1,1),W(1,13),GC_71,MDL_MSD3,MDL_WSD3,W(1,7))
C     Amplitude(s) for diagram number 120
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,7),GC_513,GC_108,AMP(129))
      CALL VSS1_3(W(1,1),W(1,13),GC_73,MDL_MSD6,MDL_WSD6,W(1,10))
C     Amplitude(s) for diagram number 121
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,10),GC_533,GC_528,AMP(130))
      CALL FFV1_2(W(1,12),W(1,1),-GC_8,MDL_MGO,MDL_WGO,W(1,16))
C     Amplitude(s) for diagram number 122
      CALL FFS1_2_0(W(1,16),W(1,5),W(1,13),GC_513,GC_108,AMP(131))
      CALL VSS1_2(W(1,1),W(1,15),GC_79,MDL_MSD3,MDL_WSD3,W(1,23))
C     Amplitude(s) for diagram number 123
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,23),GC_513,GC_108,AMP(132))
      CALL VSS1_3(W(1,1),W(1,15),GC_81,MDL_MSD6,MDL_WSD6,W(1,14))
C     Amplitude(s) for diagram number 124
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,14),GC_533,GC_528,AMP(133))
C     Amplitude(s) for diagram number 125
      CALL FFS1_2_0(W(1,16),W(1,5),W(1,15),GC_533,GC_528,AMP(134))
C     Amplitude(s) for diagram number 126
      CALL VVSS1_0(W(1,1),W(1,11),W(1,13),W(1,3),GC_18,AMP(135))
      CALL VVSS1_0(W(1,1),W(1,11),W(1,13),W(1,3),GC_18,AMP(136))
C     Amplitude(s) for diagram number 127
      CALL VSS1_0(W(1,11),W(1,7),W(1,3),GC_71,AMP(137))
C     Amplitude(s) for diagram number 128
      CALL VSS1_0(W(1,11),W(1,3),W(1,10),GC_79,AMP(138))
C     Amplitude(s) for diagram number 129
      CALL VSS1_0(W(1,21),W(1,13),W(1,3),GC_71,AMP(139))
C     Amplitude(s) for diagram number 130
      CALL VVSS1_0(W(1,1),W(1,11),W(1,3),W(1,15),GC_21,AMP(140))
      CALL VVSS1_0(W(1,1),W(1,11),W(1,3),W(1,15),GC_21,AMP(141))
C     Amplitude(s) for diagram number 131
      CALL VSS1_0(W(1,11),W(1,23),W(1,3),GC_71,AMP(142))
C     Amplitude(s) for diagram number 132
      CALL VSS1_0(W(1,11),W(1,3),W(1,14),GC_79,AMP(143))
C     Amplitude(s) for diagram number 133
      CALL VSS1_0(W(1,21),W(1,3),W(1,15),GC_79,AMP(144))
      CALL FFV1_1(W(1,17),W(1,1),GC_7,MDL_MB,ZERO,W(1,15))
C     Amplitude(s) for diagram number 134
      CALL FFV1_0(W(1,6),W(1,15),W(1,8),GC_7,AMP(145))
      CALL VVV1P0_1(W(1,1),W(1,8),GC_6,ZERO,ZERO,W(1,14))
C     Amplitude(s) for diagram number 135
      CALL FFV1_0(W(1,6),W(1,17),W(1,14),GC_7,AMP(146))
C     Amplitude(s) for diagram number 136
      CALL FFS1_2_0(W(1,12),W(1,15),W(1,4),GC_513,GC_108,AMP(147))
C     Amplitude(s) for diagram number 137
      CALL FFS1_2_0(W(1,16),W(1,17),W(1,4),GC_513,GC_108,AMP(148))
      CALL FFV1_2(W(1,20),W(1,1),GC_7,MDL_MB,ZERO,W(1,15))
C     Amplitude(s) for diagram number 138
      CALL FFV1_0(W(1,15),W(1,5),W(1,8),GC_7,AMP(149))
C     Amplitude(s) for diagram number 139
      CALL FFV1_0(W(1,20),W(1,5),W(1,14),GC_7,AMP(150))
C     Amplitude(s) for diagram number 140
      CALL FFS1_2_0(W(1,15),W(1,9),W(1,3),GC_108,GC_513,AMP(151))
C     Amplitude(s) for diagram number 141
      CALL FFS1_2_0(W(1,20),W(1,24),W(1,3),GC_108,GC_513,AMP(152))
C     Amplitude(s) for diagram number 142
      CALL VVVV1_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_96,AMP(153))
      CALL VVVV3_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_96,AMP(154))
      CALL VVVV4_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_96,AMP(155))
C     Amplitude(s) for diagram number 143
      CALL VVV1_0(W(1,2),W(1,11),W(1,14),GC_6,AMP(156))
C     Amplitude(s) for diagram number 144
      CALL VVV1_0(W(1,2),W(1,8),W(1,21),GC_6,AMP(157))
C     Amplitude(s) for diagram number 145
      CALL FFV1_0(W(1,16),W(1,9),W(1,2),GC_8,AMP(158))
C     Amplitude(s) for diagram number 146
      CALL FFV1_0(W(1,12),W(1,24),W(1,2),GC_8,AMP(159))
      CALL VVSS1_3(W(1,1),W(1,2),W(1,3),GC_18,MDL_MSD3,MDL_WSD3,W(1,24)
     $ )
      CALL VVSS1_3(W(1,1),W(1,2),W(1,3),GC_18,MDL_MSD3,MDL_WSD3,W(1,16)
     $ )
C     Amplitude(s) for diagram number 147
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,24),GC_108,GC_513,AMP(160))
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,16),GC_108,GC_513,AMP(161))
      CALL VVSS1_4(W(1,1),W(1,2),W(1,3),GC_21,MDL_MSD6,MDL_WSD6,W(1,21)
     $ )
      CALL VVSS1_4(W(1,1),W(1,2),W(1,3),GC_21,MDL_MSD6,MDL_WSD6,W(1,8))
C     Amplitude(s) for diagram number 148
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,21),GC_528,GC_533,AMP(162))
      CALL FFS1_2_0(W(1,6),W(1,9),W(1,8),GC_528,GC_533,AMP(163))
C     Amplitude(s) for diagram number 149
      CALL VSS1_0(W(1,11),W(1,4),W(1,24),GC_71,AMP(164))
      CALL VSS1_0(W(1,11),W(1,4),W(1,16),GC_71,AMP(165))
C     Amplitude(s) for diagram number 150
      CALL VSS1_0(W(1,11),W(1,4),W(1,21),GC_73,AMP(166))
      CALL VSS1_0(W(1,11),W(1,4),W(1,8),GC_73,AMP(167))
      CALL VVSS1_4(W(1,1),W(1,2),W(1,4),GC_18,MDL_MSD3,MDL_WSD3,W(1,8))
      CALL VVSS1_4(W(1,1),W(1,2),W(1,4),GC_18,MDL_MSD3,MDL_WSD3,W(1,21)
     $ )
C     Amplitude(s) for diagram number 151
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,8),GC_513,GC_108,AMP(168))
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,21),GC_513,GC_108,AMP(169))
      CALL VVSS1_4(W(1,1),W(1,2),W(1,4),GC_21,MDL_MSD6,MDL_WSD6,W(1,16)
     $ )
      CALL VVSS1_4(W(1,1),W(1,2),W(1,4),GC_21,MDL_MSD6,MDL_WSD6,W(1,24)
     $ )
C     Amplitude(s) for diagram number 152
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,16),GC_533,GC_528,AMP(170))
      CALL FFS1_2_0(W(1,12),W(1,5),W(1,24),GC_533,GC_528,AMP(171))
C     Amplitude(s) for diagram number 153
      CALL VSS1_0(W(1,11),W(1,8),W(1,3),GC_71,AMP(172))
      CALL VSS1_0(W(1,11),W(1,21),W(1,3),GC_71,AMP(173))
C     Amplitude(s) for diagram number 154
      CALL VSS1_0(W(1,11),W(1,3),W(1,16),GC_79,AMP(174))
      CALL VSS1_0(W(1,11),W(1,3),W(1,24),GC_79,AMP(175))
      CALL VVSS1P0_1(W(1,1),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,24))
      CALL VVSS1P0_1(W(1,1),W(1,4),W(1,3),GC_18,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 155
      CALL FFV1_0(W(1,6),W(1,17),W(1,24),GC_7,AMP(176))
      CALL FFV1_0(W(1,6),W(1,17),W(1,16),GC_7,AMP(177))
C     Amplitude(s) for diagram number 156
      CALL FFV1_0(W(1,20),W(1,5),W(1,24),GC_7,AMP(178))
      CALL FFV1_0(W(1,20),W(1,5),W(1,16),GC_7,AMP(179))
C     Amplitude(s) for diagram number 157
      CALL VVV1_0(W(1,24),W(1,2),W(1,11),GC_6,AMP(180))
      CALL VVV1_0(W(1,16),W(1,2),W(1,11),GC_6,AMP(181))
C     Amplitude(s) for diagram number 158
      CALL VVV1_0(W(1,1),W(1,25),W(1,11),GC_6,AMP(182))
      CALL VVV1_0(W(1,1),W(1,18),W(1,11),GC_6,AMP(183))
C     JAMPs contributing to orders ALL_ORDERS=1
      JAMP(1,1)=+1D0/2D0*(+IMAG1*AMP(4)+IMAG1*AMP(5)+AMP(7)+IMAG1
     $ *AMP(8)+IMAG1*AMP(9)-1D0/3D0*IMAG1*AMP(11)-1D0/3D0*IMAG1*AMP(12)
     $ -1D0/3D0*IMAG1*AMP(13)-1D0/3D0*IMAG1*AMP(14)-1D0/3D0*IMAG1
     $ *AMP(15)-1D0/3D0*IMAG1*AMP(16)-AMP(17)-AMP(18)-AMP(19)-AMP(20)
     $ +1D0/3D0*AMP(21)+1D0/3D0*AMP(22)+1D0/3D0*AMP(23)+1D0/3D0*AMP(24)
     $ -AMP(33)-AMP(34)+IMAG1*AMP(35)-AMP(36)-AMP(37)+IMAG1*AMP(38)
     $ +1D0/3D0*AMP(39)+1D0/3D0*AMP(40)+1D0/3D0*AMP(41)+1D0/3D0*AMP(42)
     $ +1D0/3D0*AMP(44)+1D0/3D0*AMP(45)+1D0/3D0*AMP(46)+1D0/3D0*AMP(47)
     $ -AMP(129)-AMP(130)-IMAG1*AMP(131)-AMP(132)-AMP(133)-IMAG1
     $ *AMP(134)+1D0/3D0*AMP(135)+1D0/3D0*AMP(136)+1D0/3D0*AMP(137)
     $ +1D0/3D0*AMP(138)+1D0/3D0*AMP(140)+1D0/3D0*AMP(141)+1D0/3D0
     $ *AMP(142)+1D0/3D0*AMP(143)-AMP(158)-AMP(161)-AMP(163)+1D0/3D0
     $ *AMP(165)+1D0/3D0*AMP(167)-AMP(169)-AMP(171)+1D0/3D0*AMP(173)
     $ +1D0/3D0*AMP(175))
      JAMP(2,1)=+1D0/2D0*(+IMAG1*AMP(2)-AMP(3)-1D0/3D0*IMAG1*AMP(8)
     $ -1D0/3D0*IMAG1*AMP(9)-1D0/3D0*IMAG1*AMP(10)+IMAG1*AMP(12)+IMAG1
     $ *AMP(13)+IMAG1*AMP(14)-AMP(29)-AMP(30)+1D0/3D0*AMP(31)+1D0/3D0
     $ *AMP(32)+1D0/3D0*AMP(33)+1D0/3D0*AMP(34)+1D0/3D0*AMP(36)+1D0
     $ /3D0*AMP(37)-AMP(40)-AMP(41)-AMP(42)+IMAG1*AMP(43)-AMP(45)
     $ -AMP(46)-AMP(47)+IMAG1*AMP(48)-AMP(149)-IMAG1*AMP(150)+1D0/3D0
     $ *AMP(151)-AMP(153)-AMP(154)-AMP(156)+1D0/3D0*AMP(161)+1D0/3D0
     $ *AMP(163)-AMP(165)-AMP(167)-AMP(178)+IMAG1*AMP(180))
      JAMP(3,1)=+1D0/2D0*(+IMAG1*AMP(1)+AMP(3)-1D0/3D0*IMAG1*AMP(4)
     $ -1D0/3D0*IMAG1*AMP(5)-1D0/3D0*IMAG1*AMP(6)+IMAG1*AMP(11)+IMAG1
     $ *AMP(15)+IMAG1*AMP(16)-AMP(85)-AMP(86)+1D0/3D0*AMP(87)+1D0/3D0
     $ *AMP(88)-AMP(91)+IMAG1*AMP(92)+1D0/3D0*AMP(93)-AMP(96)+1D0/3D0
     $ *AMP(129)+1D0/3D0*AMP(130)+1D0/3D0*AMP(132)+1D0/3D0*AMP(133)
     $ -AMP(135)-AMP(137)-AMP(138)-IMAG1*AMP(139)-AMP(140)-AMP(142)
     $ -AMP(143)-IMAG1*AMP(144)+AMP(153)-AMP(155)-AMP(157)+1D0/3D0
     $ *AMP(169)+1D0/3D0*AMP(171)-AMP(173)-AMP(175)+IMAG1*AMP(183))
      JAMP(4,1)=+1D0/2D0*(-1D0/3D0*IMAG1*AMP(1)-1D0/3D0*IMAG1*AMP(2)
     $ +IMAG1*AMP(6)-AMP(7)+IMAG1*AMP(10)-AMP(89)+1D0/3D0*AMP(90)+1D0
     $ /3D0*AMP(91)-AMP(93)-IMAG1*AMP(94)+1D0/3D0*AMP(149)-AMP(151)
     $ -IMAG1*AMP(152)+AMP(159))
      JAMP(5,1)=+1D0/2D0*(+1D0/3D0*AMP(25)-AMP(26)+1D0/3D0*AMP(27)
     $ -AMP(28)+1D0/3D0*AMP(29)+1D0/3D0*AMP(30)-AMP(31)-AMP(32)-IMAG1
     $ *AMP(35)-IMAG1*AMP(38)+1D0/3D0*AMP(57)+1D0/3D0*AMP(58)-AMP(59)
     $ -AMP(60)+1D0/3D0*AMP(61)-AMP(62)+1D0/3D0*AMP(63)-AMP(64)-IMAG1
     $ *AMP(67)-IMAG1*AMP(70)-IMAG1*AMP(148)+IMAG1*AMP(152)+AMP(158)
     $ -AMP(159)+1D0/3D0*AMP(177)+1D0/3D0*AMP(176)+1D0/3D0*AMP(179)
     $ +1D0/3D0*AMP(178))
      JAMP(6,1)=+1D0/2D0*(+1D0/3D0*AMP(17)+1D0/3D0*AMP(18)+1D0/3D0
     $ *AMP(19)+1D0/3D0*AMP(20)-AMP(21)-AMP(22)-AMP(23)-AMP(24)-AMP(25)
     $ +1D0/3D0*AMP(26)-AMP(27)+1D0/3D0*AMP(28)-AMP(39)-IMAG1*AMP(43)
     $ -AMP(44)-IMAG1*AMP(48)+1D0/3D0*AMP(101)-AMP(102)+1D0/3D0
     $ *AMP(103)-AMP(104)+1D0/3D0*AMP(105)-AMP(106)+IMAG1*AMP(108)
     $ -AMP(112)-AMP(136)+IMAG1*AMP(139)-AMP(141)+IMAG1*AMP(144)-IMAG1
     $ *AMP(146)+AMP(154)+AMP(155)+AMP(156)+AMP(157)-AMP(176)-IMAG1
     $ *AMP(180)-IMAG1*AMP(183))
      JAMP(7,1)=+1D0/2D0*(+1D0/3D0*AMP(49)+1D0/3D0*AMP(50)+1D0/3D0
     $ *AMP(51)+1D0/3D0*AMP(52)-AMP(53)-AMP(54)-AMP(55)-AMP(56)-AMP(61)
     $ +1D0/3D0*AMP(62)-AMP(63)+1D0/3D0*AMP(64)-AMP(72)+IMAG1*AMP(75)
     $ -AMP(77)+IMAG1*AMP(80)+1D0/3D0*AMP(81)-AMP(82)+1D0/3D0*AMP(83)
     $ -AMP(84)+1D0/3D0*AMP(89)-AMP(90)-IMAG1*AMP(92)-AMP(95)-AMP(119)
     $ -IMAG1*AMP(123)-AMP(124)-IMAG1*AMP(128)+IMAG1*AMP(150)+AMP(154)
     $ +AMP(155)+AMP(156)+AMP(157)-AMP(179)+IMAG1*AMP(181)+IMAG1
     $ *AMP(182))
      JAMP(8,1)=+1D0/2D0*(-AMP(81)+1D0/3D0*AMP(82)-AMP(83)+1D0/3D0
     $ *AMP(84)+1D0/3D0*AMP(85)+1D0/3D0*AMP(86)-AMP(87)-AMP(88)+IMAG1
     $ *AMP(94)+1D0/3D0*AMP(96)+1D0/3D0*AMP(95)+1D0/3D0*AMP(97)+1D0
     $ /3D0*AMP(98)-AMP(99)-AMP(100)-AMP(101)+1D0/3D0*AMP(102)-AMP(103)
     $ +1D0/3D0*AMP(104)+IMAG1*AMP(110)+1D0/3D0*AMP(112)+1D0/3D0
     $ *AMP(111)-IMAG1*AMP(115)-IMAG1*AMP(118)+IMAG1*AMP(131)+IMAG1
     $ *AMP(134)+AMP(158)-AMP(159))
      JAMP(9,1)=+1D0/2D0*(-IMAG1*AMP(4)-IMAG1*AMP(5)-AMP(7)-IMAG1
     $ *AMP(8)-IMAG1*AMP(9)+1D0/3D0*IMAG1*AMP(11)+1D0/3D0*IMAG1*AMP(12)
     $ +1D0/3D0*IMAG1*AMP(13)+1D0/3D0*IMAG1*AMP(14)+1D0/3D0*IMAG1
     $ *AMP(15)+1D0/3D0*IMAG1*AMP(16)-AMP(49)-AMP(50)-AMP(51)-AMP(52)
     $ +1D0/3D0*AMP(53)+1D0/3D0*AMP(54)+1D0/3D0*AMP(55)+1D0/3D0*AMP(56)
     $ -AMP(65)-AMP(66)+IMAG1*AMP(67)-AMP(68)-AMP(69)+IMAG1*AMP(70)
     $ +1D0/3D0*AMP(71)+1D0/3D0*AMP(72)+1D0/3D0*AMP(73)+1D0/3D0*AMP(74)
     $ +1D0/3D0*AMP(76)+1D0/3D0*AMP(77)+1D0/3D0*AMP(78)+1D0/3D0*AMP(79)
     $ -AMP(113)-AMP(114)+IMAG1*AMP(115)-AMP(116)-AMP(117)+IMAG1
     $ *AMP(118)+1D0/3D0*AMP(119)+1D0/3D0*AMP(120)+1D0/3D0*AMP(121)
     $ +1D0/3D0*AMP(122)+1D0/3D0*AMP(124)+1D0/3D0*AMP(125)+1D0/3D0
     $ *AMP(126)+1D0/3D0*AMP(127)+AMP(159)-AMP(160)-AMP(162)+1D0/3D0
     $ *AMP(164)+1D0/3D0*AMP(166)-AMP(168)-AMP(170)+1D0/3D0*AMP(172)
     $ +1D0/3D0*AMP(174))
      JAMP(10,1)=+1D0/2D0*(-IMAG1*AMP(2)+AMP(3)+1D0/3D0*IMAG1*AMP(8)
     $ +1D0/3D0*IMAG1*AMP(9)+1D0/3D0*IMAG1*AMP(10)-IMAG1*AMP(12)-IMAG1
     $ *AMP(13)-IMAG1*AMP(14)-AMP(97)-AMP(98)+1D0/3D0*AMP(99)+1D0/3D0
     $ *AMP(100)-AMP(107)-IMAG1*AMP(108)+1D0/3D0*AMP(109)-AMP(111)+1D0
     $ /3D0*AMP(113)+1D0/3D0*AMP(114)+1D0/3D0*AMP(116)+1D0/3D0*AMP(117)
     $ -AMP(120)-AMP(121)-AMP(122)+IMAG1*AMP(123)-AMP(125)-AMP(126)
     $ -AMP(127)+IMAG1*AMP(128)+AMP(153)-AMP(155)-AMP(157)+1D0/3D0
     $ *AMP(160)+1D0/3D0*AMP(162)-AMP(164)-AMP(166)-IMAG1*AMP(182))
      JAMP(11,1)=+1D0/2D0*(-IMAG1*AMP(1)-AMP(3)+1D0/3D0*IMAG1*AMP(4)
     $ +1D0/3D0*IMAG1*AMP(5)+1D0/3D0*IMAG1*AMP(6)-IMAG1*AMP(11)-IMAG1
     $ *AMP(15)-IMAG1*AMP(16)-AMP(57)-AMP(58)+1D0/3D0*AMP(59)+1D0/3D0
     $ *AMP(60)+1D0/3D0*AMP(65)+1D0/3D0*AMP(66)+1D0/3D0*AMP(68)+1D0
     $ /3D0*AMP(69)-AMP(71)-AMP(73)-AMP(74)-IMAG1*AMP(75)-AMP(76)
     $ -AMP(78)-AMP(79)-IMAG1*AMP(80)-AMP(145)+IMAG1*AMP(146)+1D0/3D0
     $ *AMP(147)-AMP(153)-AMP(154)-AMP(156)+1D0/3D0*AMP(168)+1D0/3D0
     $ *AMP(170)-AMP(172)-AMP(174)-AMP(177)-IMAG1*AMP(181))
      JAMP(12,1)=+1D0/2D0*(+1D0/3D0*IMAG1*AMP(1)+1D0/3D0*IMAG1*AMP(2)
     $ -IMAG1*AMP(6)+AMP(7)-IMAG1*AMP(10)-AMP(105)+1D0/3D0*AMP(106)
     $ +1D0/3D0*AMP(107)-AMP(109)-IMAG1*AMP(110)+1D0/3D0*AMP(145)
     $ -AMP(147)+IMAG1*AMP(148)-AMP(158))

      MATRIX1 = 0.D0
      DO M = 1, NAMPSO
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX1(M,N))) THEN
              MATRIX1 = MATRIX1 + ZTEMP*DCONJG(JAMP(I,N))/DENOM(I)
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
      AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
      AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
      AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
      AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
      AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
      AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
      AMP2(12)=AMP2(12)+AMP(13)*DCONJG(AMP(13))
      AMP2(13)=AMP2(13)+AMP(14)*DCONJG(AMP(14))
      AMP2(14)=AMP2(14)+AMP(15)*DCONJG(AMP(15))
      AMP2(15)=AMP2(15)+AMP(16)*DCONJG(AMP(16))
      AMP2(16)=AMP2(16)+AMP(17)*DCONJG(AMP(17))
      AMP2(17)=AMP2(17)+AMP(18)*DCONJG(AMP(18))
      AMP2(18)=AMP2(18)+AMP(19)*DCONJG(AMP(19))
      AMP2(19)=AMP2(19)+AMP(20)*DCONJG(AMP(20))
      AMP2(20)=AMP2(20)+AMP(21)*DCONJG(AMP(21))
      AMP2(21)=AMP2(21)+AMP(22)*DCONJG(AMP(22))
      AMP2(22)=AMP2(22)+AMP(23)*DCONJG(AMP(23))
      AMP2(23)=AMP2(23)+AMP(24)*DCONJG(AMP(24))
      AMP2(24)=AMP2(24)+AMP(25)*DCONJG(AMP(25))
      AMP2(25)=AMP2(25)+AMP(26)*DCONJG(AMP(26))
      AMP2(26)=AMP2(26)+AMP(27)*DCONJG(AMP(27))
      AMP2(27)=AMP2(27)+AMP(28)*DCONJG(AMP(28))
      AMP2(28)=AMP2(28)+AMP(29)*DCONJG(AMP(29))
      AMP2(29)=AMP2(29)+AMP(30)*DCONJG(AMP(30))
      AMP2(30)=AMP2(30)+AMP(31)*DCONJG(AMP(31))
      AMP2(31)=AMP2(31)+AMP(32)*DCONJG(AMP(32))
      AMP2(32)=AMP2(32)+AMP(33)*DCONJG(AMP(33))
      AMP2(33)=AMP2(33)+AMP(34)*DCONJG(AMP(34))
      AMP2(34)=AMP2(34)+AMP(35)*DCONJG(AMP(35))
      AMP2(35)=AMP2(35)+AMP(36)*DCONJG(AMP(36))
      AMP2(36)=AMP2(36)+AMP(37)*DCONJG(AMP(37))
      AMP2(37)=AMP2(37)+AMP(38)*DCONJG(AMP(38))
      AMP2(39)=AMP2(39)+AMP(41)*DCONJG(AMP(41))
      AMP2(40)=AMP2(40)+AMP(42)*DCONJG(AMP(42))
      AMP2(41)=AMP2(41)+AMP(43)*DCONJG(AMP(43))
      AMP2(43)=AMP2(43)+AMP(46)*DCONJG(AMP(46))
      AMP2(44)=AMP2(44)+AMP(47)*DCONJG(AMP(47))
      AMP2(45)=AMP2(45)+AMP(48)*DCONJG(AMP(48))
      AMP2(46)=AMP2(46)+AMP(49)*DCONJG(AMP(49))
      AMP2(47)=AMP2(47)+AMP(50)*DCONJG(AMP(50))
      AMP2(48)=AMP2(48)+AMP(51)*DCONJG(AMP(51))
      AMP2(49)=AMP2(49)+AMP(52)*DCONJG(AMP(52))
      AMP2(50)=AMP2(50)+AMP(53)*DCONJG(AMP(53))
      AMP2(51)=AMP2(51)+AMP(54)*DCONJG(AMP(54))
      AMP2(52)=AMP2(52)+AMP(55)*DCONJG(AMP(55))
      AMP2(53)=AMP2(53)+AMP(56)*DCONJG(AMP(56))
      AMP2(54)=AMP2(54)+AMP(57)*DCONJG(AMP(57))
      AMP2(55)=AMP2(55)+AMP(58)*DCONJG(AMP(58))
      AMP2(56)=AMP2(56)+AMP(59)*DCONJG(AMP(59))
      AMP2(57)=AMP2(57)+AMP(60)*DCONJG(AMP(60))
      AMP2(58)=AMP2(58)+AMP(61)*DCONJG(AMP(61))
      AMP2(59)=AMP2(59)+AMP(62)*DCONJG(AMP(62))
      AMP2(60)=AMP2(60)+AMP(63)*DCONJG(AMP(63))
      AMP2(61)=AMP2(61)+AMP(64)*DCONJG(AMP(64))
      AMP2(62)=AMP2(62)+AMP(65)*DCONJG(AMP(65))
      AMP2(63)=AMP2(63)+AMP(66)*DCONJG(AMP(66))
      AMP2(64)=AMP2(64)+AMP(67)*DCONJG(AMP(67))
      AMP2(65)=AMP2(65)+AMP(68)*DCONJG(AMP(68))
      AMP2(66)=AMP2(66)+AMP(69)*DCONJG(AMP(69))
      AMP2(67)=AMP2(67)+AMP(70)*DCONJG(AMP(70))
      AMP2(69)=AMP2(69)+AMP(73)*DCONJG(AMP(73))
      AMP2(70)=AMP2(70)+AMP(74)*DCONJG(AMP(74))
      AMP2(71)=AMP2(71)+AMP(75)*DCONJG(AMP(75))
      AMP2(73)=AMP2(73)+AMP(78)*DCONJG(AMP(78))
      AMP2(74)=AMP2(74)+AMP(79)*DCONJG(AMP(79))
      AMP2(75)=AMP2(75)+AMP(80)*DCONJG(AMP(80))
      AMP2(76)=AMP2(76)+AMP(81)*DCONJG(AMP(81))
      AMP2(77)=AMP2(77)+AMP(82)*DCONJG(AMP(82))
      AMP2(78)=AMP2(78)+AMP(83)*DCONJG(AMP(83))
      AMP2(79)=AMP2(79)+AMP(84)*DCONJG(AMP(84))
      AMP2(80)=AMP2(80)+AMP(85)*DCONJG(AMP(85))
      AMP2(81)=AMP2(81)+AMP(86)*DCONJG(AMP(86))
      AMP2(82)=AMP2(82)+AMP(87)*DCONJG(AMP(87))
      AMP2(83)=AMP2(83)+AMP(88)*DCONJG(AMP(88))
      AMP2(84)=AMP2(84)+AMP(89)*DCONJG(AMP(89))
      AMP2(85)=AMP2(85)+AMP(90)*DCONJG(AMP(90))
      AMP2(86)=AMP2(86)+AMP(91)*DCONJG(AMP(91))
      AMP2(87)=AMP2(87)+AMP(92)*DCONJG(AMP(92))
      AMP2(88)=AMP2(88)+AMP(93)*DCONJG(AMP(93))
      AMP2(89)=AMP2(89)+AMP(94)*DCONJG(AMP(94))
      AMP2(91)=AMP2(91)+AMP(97)*DCONJG(AMP(97))
      AMP2(92)=AMP2(92)+AMP(98)*DCONJG(AMP(98))
      AMP2(93)=AMP2(93)+AMP(99)*DCONJG(AMP(99))
      AMP2(94)=AMP2(94)+AMP(100)*DCONJG(AMP(100))
      AMP2(95)=AMP2(95)+AMP(101)*DCONJG(AMP(101))
      AMP2(96)=AMP2(96)+AMP(102)*DCONJG(AMP(102))
      AMP2(97)=AMP2(97)+AMP(103)*DCONJG(AMP(103))
      AMP2(98)=AMP2(98)+AMP(104)*DCONJG(AMP(104))
      AMP2(99)=AMP2(99)+AMP(105)*DCONJG(AMP(105))
      AMP2(100)=AMP2(100)+AMP(106)*DCONJG(AMP(106))
      AMP2(101)=AMP2(101)+AMP(107)*DCONJG(AMP(107))
      AMP2(102)=AMP2(102)+AMP(108)*DCONJG(AMP(108))
      AMP2(103)=AMP2(103)+AMP(109)*DCONJG(AMP(109))
      AMP2(104)=AMP2(104)+AMP(110)*DCONJG(AMP(110))
      AMP2(106)=AMP2(106)+AMP(113)*DCONJG(AMP(113))
      AMP2(107)=AMP2(107)+AMP(114)*DCONJG(AMP(114))
      AMP2(108)=AMP2(108)+AMP(115)*DCONJG(AMP(115))
      AMP2(109)=AMP2(109)+AMP(116)*DCONJG(AMP(116))
      AMP2(110)=AMP2(110)+AMP(117)*DCONJG(AMP(117))
      AMP2(111)=AMP2(111)+AMP(118)*DCONJG(AMP(118))
      AMP2(113)=AMP2(113)+AMP(121)*DCONJG(AMP(121))
      AMP2(114)=AMP2(114)+AMP(122)*DCONJG(AMP(122))
      AMP2(115)=AMP2(115)+AMP(123)*DCONJG(AMP(123))
      AMP2(117)=AMP2(117)+AMP(126)*DCONJG(AMP(126))
      AMP2(118)=AMP2(118)+AMP(127)*DCONJG(AMP(127))
      AMP2(119)=AMP2(119)+AMP(128)*DCONJG(AMP(128))
      AMP2(120)=AMP2(120)+AMP(129)*DCONJG(AMP(129))
      AMP2(121)=AMP2(121)+AMP(130)*DCONJG(AMP(130))
      AMP2(122)=AMP2(122)+AMP(131)*DCONJG(AMP(131))
      AMP2(123)=AMP2(123)+AMP(132)*DCONJG(AMP(132))
      AMP2(124)=AMP2(124)+AMP(133)*DCONJG(AMP(133))
      AMP2(125)=AMP2(125)+AMP(134)*DCONJG(AMP(134))
      AMP2(127)=AMP2(127)+AMP(137)*DCONJG(AMP(137))
      AMP2(128)=AMP2(128)+AMP(138)*DCONJG(AMP(138))
      AMP2(129)=AMP2(129)+AMP(139)*DCONJG(AMP(139))
      AMP2(131)=AMP2(131)+AMP(142)*DCONJG(AMP(142))
      AMP2(132)=AMP2(132)+AMP(143)*DCONJG(AMP(143))
      AMP2(133)=AMP2(133)+AMP(144)*DCONJG(AMP(144))
      AMP2(134)=AMP2(134)+AMP(145)*DCONJG(AMP(145))
      AMP2(135)=AMP2(135)+AMP(146)*DCONJG(AMP(146))
      AMP2(136)=AMP2(136)+AMP(147)*DCONJG(AMP(147))
      AMP2(137)=AMP2(137)+AMP(148)*DCONJG(AMP(148))
      AMP2(138)=AMP2(138)+AMP(149)*DCONJG(AMP(149))
      AMP2(139)=AMP2(139)+AMP(150)*DCONJG(AMP(150))
      AMP2(140)=AMP2(140)+AMP(151)*DCONJG(AMP(151))
      AMP2(141)=AMP2(141)+AMP(152)*DCONJG(AMP(152))
      AMP2(143)=AMP2(143)+AMP(156)*DCONJG(AMP(156))
      AMP2(144)=AMP2(144)+AMP(157)*DCONJG(AMP(157))
      AMP2(145)=AMP2(145)+AMP(158)*DCONJG(AMP(158))
      AMP2(146)=AMP2(146)+AMP(159)*DCONJG(AMP(159))
      DO I = 1, NCOLOR
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            IF (CHOSEN_SO_CONFIGS(SQSOINDEX1(M,N))) THEN
              JAMP2(I)=JAMP2(I)+DABS(DBLE(JAMP(I,M)*DCONJG(JAMP(I,N))))
            ENDIF
          ENDDO
        ENDDO
      ENDDO

      END

C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX1(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    1/
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS1
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)+AMPSPLITORDERS(ORDERI
     $NDEXB,I)
      ENDDO
      SQSOINDEX1=SOINDEX_FOR_SQUARED_ORDERS1(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN1(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS1/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_SQUARED_ORDERS_FOR_SOIN'
     $ //'DEX1'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX1(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX1'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS1(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS1/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS1 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS1'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

